/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CoreVaultManager__factory } from "./CoreVaultManager__factory";
export { CoreVaultManagerProxy__factory } from "./CoreVaultManagerProxy__factory";
