/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentVaultFactory,
  IAgentVaultFactoryInterface,
} from "../../../../contracts/assetManager/interfaces/IAgentVaultFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IIAssetManager",
        name: "_assetManager",
        type: "address",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "contract IIAgentVault",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_proxy",
        type: "address",
      },
    ],
    name: "upgradeInitCall",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgentVaultFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentVaultFactoryInterface {
    return new Interface(_abi) as IAgentVaultFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentVaultFactory {
    return new Contract(address, _abi, runner) as unknown as IAgentVaultFactory;
  }
}
