/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IIAssetManager__factory } from "./IIAssetManager__factory";
export { IISettingsManagement__factory } from "./IISettingsManagement__factory";
