/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CheckPointableMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceHistoryCleanup"
      | "balanceOfAt"
      | "burnForAtNow"
      | "cleanerContract"
      | "getCleanupBlockNumber"
      | "mintForAtNow"
      | "setCleanupBlockNumber"
      | "totalSupplyAt"
      | "totalSupplyHistoryCleanup"
      | "transmitAtNow"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceHistoryCleanup",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnForAtNow",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cleanerContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCleanupBlockNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintForAtNow",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCleanupBlockNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyHistoryCleanup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transmitAtNow",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "balanceHistoryCleanup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnForAtNow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cleanerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCleanupBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintForAtNow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCleanupBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyHistoryCleanup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transmitAtNow",
    data: BytesLike
  ): Result;
}

export interface CheckPointableMock extends BaseContract {
  connect(runner?: ContractRunner | null): CheckPointableMock;
  waitForDeployment(): Promise<this>;

  interface: CheckPointableMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceHistoryCleanup: TypedContractMethod<
    [_owner: AddressLike, _count: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  balanceOfAt: TypedContractMethod<
    [_owner: AddressLike, _blockNumber: BigNumberish],
    [bigint],
    "view"
  >;

  burnForAtNow: TypedContractMethod<
    [_owner: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  cleanerContract: TypedContractMethod<[], [string], "view">;

  getCleanupBlockNumber: TypedContractMethod<[], [bigint], "view">;

  mintForAtNow: TypedContractMethod<
    [_owner: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCleanupBlockNumber: TypedContractMethod<
    [_blockNumber: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalSupplyAt: TypedContractMethod<
    [_blockNumber: BigNumberish],
    [bigint],
    "view"
  >;

  totalSupplyHistoryCleanup: TypedContractMethod<
    [_count: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  transmitAtNow: TypedContractMethod<
    [from: AddressLike, to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceHistoryCleanup"
  ): TypedContractMethod<
    [_owner: AddressLike, _count: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOfAt"
  ): TypedContractMethod<
    [_owner: AddressLike, _blockNumber: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "burnForAtNow"
  ): TypedContractMethod<
    [_owner: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cleanerContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCleanupBlockNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintForAtNow"
  ): TypedContractMethod<
    [_owner: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCleanupBlockNumber"
  ): TypedContractMethod<[_blockNumber: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalSupplyAt"
  ): TypedContractMethod<[_blockNumber: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupplyHistoryCleanup"
  ): TypedContractMethod<[_count: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "transmitAtNow"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
