/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AddressUpdatable,
  AddressUpdatableInterface,
} from "../../../../contracts/flareSmartContracts/implementation/AddressUpdatable";

const _abi = [
  {
    inputs: [],
    name: "AUAddressZero",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyAddressUpdater",
    type: "error",
  },
  {
    inputs: [],
    name: "getAddressUpdater",
    outputs: [
      {
        internalType: "address",
        name: "_addressUpdater",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_contractNameHashes",
        type: "bytes32[]",
      },
      {
        internalType: "address[]",
        name: "_contractAddresses",
        type: "address[]",
      },
    ],
    name: "updateContractAddresses",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class AddressUpdatable__factory {
  static readonly abi = _abi;
  static createInterface(): AddressUpdatableInterface {
    return new Interface(_abi) as AddressUpdatableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AddressUpdatable {
    return new Contract(address, _abi, runner) as unknown as AddressUpdatable;
  }
}
