/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUpgradableContractFactory,
  IUpgradableContractFactoryInterface,
} from "../../../../contracts/utils/interfaces/IUpgradableContractFactory";

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_proxy",
        type: "address",
      },
    ],
    name: "upgradeInitCall",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUpgradableContractFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IUpgradableContractFactoryInterface {
    return new Interface(_abi) as IUpgradableContractFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUpgradableContractFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUpgradableContractFactory;
  }
}
