/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace AgentSettings {
  export type DataStruct = {
    vaultCollateralToken: AddressLike;
    poolTokenSuffix: string;
    feeBIPS: BigNumberish;
    poolFeeShareBIPS: BigNumberish;
    mintingVaultCollateralRatioBIPS: BigNumberish;
    mintingPoolCollateralRatioBIPS: BigNumberish;
    buyFAssetByAgentFactorBIPS: BigNumberish;
    poolExitCollateralRatioBIPS: BigNumberish;
    redemptionPoolFeeShareBIPS: BigNumberish;
  };

  export type DataStructOutput = [
    vaultCollateralToken: string,
    poolTokenSuffix: string,
    feeBIPS: bigint,
    poolFeeShareBIPS: bigint,
    mintingVaultCollateralRatioBIPS: bigint,
    mintingPoolCollateralRatioBIPS: bigint,
    buyFAssetByAgentFactorBIPS: bigint,
    poolExitCollateralRatioBIPS: bigint,
    redemptionPoolFeeShareBIPS: bigint
  ] & {
    vaultCollateralToken: string;
    poolTokenSuffix: string;
    feeBIPS: bigint;
    poolFeeShareBIPS: bigint;
    mintingVaultCollateralRatioBIPS: bigint;
    mintingPoolCollateralRatioBIPS: bigint;
    buyFAssetByAgentFactorBIPS: bigint;
    poolExitCollateralRatioBIPS: bigint;
    redemptionPoolFeeShareBIPS: bigint;
  };
}

export interface IICollateralPoolFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "create" | "implementation" | "upgradeInitCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "create",
    values: [AddressLike, AddressLike, AgentSettings.DataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeInitCall",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeInitCall",
    data: BytesLike
  ): Result;
}

export interface IICollateralPoolFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IICollateralPoolFactory;
  waitForDeployment(): Promise<this>;

  interface: IICollateralPoolFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  create: TypedContractMethod<
    [
      _assetManager: AddressLike,
      _agentVault: AddressLike,
      _settings: AgentSettings.DataStruct
    ],
    [string],
    "nonpayable"
  >;

  implementation: TypedContractMethod<[], [string], "view">;

  upgradeInitCall: TypedContractMethod<[_proxy: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<
    [
      _assetManager: AddressLike,
      _agentVault: AddressLike,
      _settings: AgentSettings.DataStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeInitCall"
  ): TypedContractMethod<[_proxy: AddressLike], [string], "view">;

  filters: {};
}
