/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IICollateralPool } from "./IICollateralPool";
export type { IICollateralPoolFactory } from "./IICollateralPoolFactory";
export type { IICollateralPoolToken } from "./IICollateralPoolToken";
export type { IICollateralPoolTokenFactory } from "./IICollateralPoolTokenFactory";
