/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IPayment {
  export type RequestBodyStruct = {
    transactionId: BytesLike;
    inUtxo: BigNumberish;
    utxo: BigNumberish;
  };

  export type RequestBodyStructOutput = [
    transactionId: string,
    inUtxo: bigint,
    utxo: bigint
  ] & { transactionId: string; inUtxo: bigint; utxo: bigint };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    blockTimestamp: BigNumberish;
    sourceAddressHash: BytesLike;
    sourceAddressesRoot: BytesLike;
    receivingAddressHash: BytesLike;
    intendedReceivingAddressHash: BytesLike;
    spentAmount: BigNumberish;
    intendedSpentAmount: BigNumberish;
    receivedAmount: BigNumberish;
    intendedReceivedAmount: BigNumberish;
    standardPaymentReference: BytesLike;
    oneToOne: boolean;
    status: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    blockTimestamp: bigint,
    sourceAddressHash: string,
    sourceAddressesRoot: string,
    receivingAddressHash: string,
    intendedReceivingAddressHash: string,
    spentAmount: bigint,
    intendedSpentAmount: bigint,
    receivedAmount: bigint,
    intendedReceivedAmount: bigint,
    standardPaymentReference: string,
    oneToOne: boolean,
    status: bigint
  ] & {
    blockNumber: bigint;
    blockTimestamp: bigint;
    sourceAddressHash: string;
    sourceAddressesRoot: string;
    receivingAddressHash: string;
    intendedReceivingAddressHash: string;
    spentAmount: bigint;
    intendedSpentAmount: bigint;
    receivedAmount: bigint;
    intendedReceivedAmount: bigint;
    standardPaymentReference: string;
    oneToOne: boolean;
    status: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IPayment.RequestBodyStruct;
    responseBody: IPayment.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IPayment.RequestBodyStructOutput,
    responseBody: IPayment.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IPayment.RequestBodyStructOutput;
    responseBody: IPayment.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IPayment.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IPayment.ResponseStructOutput
  ] & { merkleProof: string[]; data: IPayment.ResponseStructOutput };
}

export declare namespace ICoreVaultManager {
  export type TransferRequestStruct = {
    destinationAddress: string;
    paymentReference: BytesLike;
    amount: BigNumberish;
  };

  export type TransferRequestStructOutput = [
    destinationAddress: string,
    paymentReference: string,
    amount: bigint
  ] & { destinationAddress: string; paymentReference: string; amount: bigint };

  export type EscrowStruct = {
    preimageHash: BytesLike;
    amount: BigNumberish;
    expiryTs: BigNumberish;
    finished: boolean;
  };

  export type EscrowStructOutput = [
    preimageHash: string,
    amount: bigint,
    expiryTs: bigint,
    finished: boolean
  ] & {
    preimageHash: string;
    amount: bigint;
    expiryTs: bigint;
    finished: boolean;
  };
}

export interface CoreVaultManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAllowedDestinationAddresses"
      | "addEmergencyPauseSenders"
      | "addPreimageHashes"
      | "addTriggeringAccounts"
      | "assetManager"
      | "availableFunds"
      | "cancelGovernanceCall"
      | "cancelTransferRequestFromCoreVault"
      | "chainId"
      | "confirmPayment"
      | "confirmedPayments"
      | "coreVaultAddress"
      | "coreVaultAddressHash"
      | "custodianAddress"
      | "escrowedFunds"
      | "executeGovernanceCall"
      | "fdcVerification"
      | "getAddressUpdater"
      | "getAllowedDestinationAddresses"
      | "getCancelableTransferRequests"
      | "getEmergencyPauseSenders"
      | "getEscrowByIndex"
      | "getEscrowByPreimageHash"
      | "getEscrowsCount"
      | "getNonCancelableTransferRequests"
      | "getPreimageHash"
      | "getPreimageHashesCount"
      | "getSettings"
      | "getTriggeringAccounts"
      | "getUnprocessedEscrows"
      | "getUnusedPreimageHashes"
      | "governance"
      | "governanceSettings"
      | "initialise"
      | "initialize"
      | "isDestinationAddressAllowed"
      | "isExecutor"
      | "nextSequenceNumber"
      | "nextUnprocessedEscrowIndex"
      | "nextUnusedPreimageHashIndex"
      | "pause"
      | "paused"
      | "processEscrows"
      | "productionMode"
      | "proxiableUUID"
      | "removeAllowedDestinationAddresses"
      | "removeEmergencyPauseSenders"
      | "removeTriggeringAccounts"
      | "removeUnusedPreimageHashes"
      | "requestTransferFromCoreVault"
      | "setEscrowsFinished"
      | "supportsInterface"
      | "switchToProductionMode"
      | "totalRequestAmountWithFee"
      | "triggerCustomInstructions"
      | "triggerInstructions"
      | "unpause"
      | "updateContractAddresses"
      | "updateCustodianAddress"
      | "updateSettings"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "AllowedDestinationAddressAdded"
      | "AllowedDestinationAddressRemoved"
      | "BeaconUpgraded"
      | "CustodianAddressUpdated"
      | "CustomInstructions"
      | "EmergencyPauseSenderAdded"
      | "EmergencyPauseSenderRemoved"
      | "EscrowFinished"
      | "EscrowInstructions"
      | "GovernanceCallTimelocked"
      | "GovernanceInitialised"
      | "GovernedProductionModeEntered"
      | "NotAllEscrowsProcessed"
      | "Paused"
      | "PaymentConfirmed"
      | "PaymentInstructions"
      | "PreimageHashAdded"
      | "SettingsUpdated"
      | "TimelockedGovernanceCallCanceled"
      | "TimelockedGovernanceCallExecuted"
      | "TransferRequestCanceled"
      | "TransferRequested"
      | "TriggeringAccountAdded"
      | "TriggeringAccountRemoved"
      | "Unpaused"
      | "UnusedPreimageHashRemoved"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAllowedDestinationAddresses",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addEmergencyPauseSenders",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addPreimageHashes",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addTriggeringAccounts",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assetManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelGovernanceCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransferRequestFromCoreVault",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confirmPayment",
    values: [IPayment.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmedPayments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "coreVaultAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coreVaultAddressHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "custodianAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrowedFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeGovernanceCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fdcVerification",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressUpdater",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowedDestinationAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCancelableTransferRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmergencyPauseSenders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowByPreimageHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNonCancelableTransferRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPreimageHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPreimageHashesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTriggeringAccounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnprocessedEscrows",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnusedPreimageHashes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceSettings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialise",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isDestinationAddressAllowed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSequenceNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextUnprocessedEscrowIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextUnusedPreimageHashIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processEscrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productionMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllowedDestinationAddresses",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmergencyPauseSenders",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTriggeringAccounts",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeUnusedPreimageHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTransferFromCoreVault",
    values: [string, BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowsFinished",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "switchToProductionMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRequestAmountWithFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerCustomInstructions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerInstructions",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateContractAddresses",
    values: [BytesLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCustodianAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSettings",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAllowedDestinationAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addEmergencyPauseSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPreimageHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTriggeringAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelGovernanceCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransferRequestFromCoreVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmedPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coreVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coreVaultAddressHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "custodianAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowedFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeGovernanceCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fdcVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressUpdater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedDestinationAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCancelableTransferRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmergencyPauseSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowByPreimageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNonCancelableTransferRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPreimageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPreimageHashesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTriggeringAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnprocessedEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnusedPreimageHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialise", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDestinationAddressAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExecutor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextSequenceNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextUnprocessedEscrowIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextUnusedPreimageHashIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productionMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowedDestinationAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmergencyPauseSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTriggeringAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeUnusedPreimageHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTransferFromCoreVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowsFinished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "switchToProductionMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRequestAmountWithFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerCustomInstructions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerInstructions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateContractAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCustodianAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowedDestinationAddressAddedEvent {
  export type InputTuple = [destinationAddress: string];
  export type OutputTuple = [destinationAddress: string];
  export interface OutputObject {
    destinationAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowedDestinationAddressRemovedEvent {
  export type InputTuple = [destinationAddress: string];
  export type OutputTuple = [destinationAddress: string];
  export interface OutputObject {
    destinationAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustodianAddressUpdatedEvent {
  export type InputTuple = [custodianAddress: string];
  export type OutputTuple = [custodianAddress: string];
  export interface OutputObject {
    custodianAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustomInstructionsEvent {
  export type InputTuple = [
    sequence: BigNumberish,
    account: string,
    instructionsHash: BytesLike
  ];
  export type OutputTuple = [
    sequence: bigint,
    account: string,
    instructionsHash: string
  ];
  export interface OutputObject {
    sequence: bigint;
    account: string;
    instructionsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseSenderAddedEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseSenderRemovedEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFinishedEvent {
  export type InputTuple = [preimageHash: BytesLike, amount: BigNumberish];
  export type OutputTuple = [preimageHash: string, amount: bigint];
  export interface OutputObject {
    preimageHash: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowInstructionsEvent {
  export type InputTuple = [
    sequence: BigNumberish,
    preimageHash: BytesLike,
    account: string,
    destination: string,
    amount: BigNumberish,
    fee: BigNumberish,
    cancelAfterTs: BigNumberish
  ];
  export type OutputTuple = [
    sequence: bigint,
    preimageHash: string,
    account: string,
    destination: string,
    amount: bigint,
    fee: bigint,
    cancelAfterTs: bigint
  ];
  export interface OutputObject {
    sequence: bigint;
    preimageHash: string;
    account: string;
    destination: string;
    amount: bigint;
    fee: bigint;
    cancelAfterTs: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceCallTimelockedEvent {
  export type InputTuple = [
    encodedCall: BytesLike,
    encodedCallHash: BytesLike,
    allowedAfterTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    encodedCall: string,
    encodedCallHash: string,
    allowedAfterTimestamp: bigint
  ];
  export interface OutputObject {
    encodedCall: string;
    encodedCallHash: string;
    allowedAfterTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceInitialisedEvent {
  export type InputTuple = [initialGovernance: AddressLike];
  export type OutputTuple = [initialGovernance: string];
  export interface OutputObject {
    initialGovernance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernedProductionModeEnteredEvent {
  export type InputTuple = [governanceSettings: AddressLike];
  export type OutputTuple = [governanceSettings: string];
  export interface OutputObject {
    governanceSettings: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NotAllEscrowsProcessedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentConfirmedEvent {
  export type InputTuple = [
    transactionId: BytesLike,
    paymentReference: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: string,
    paymentReference: string,
    amount: bigint
  ];
  export interface OutputObject {
    transactionId: string;
    paymentReference: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentInstructionsEvent {
  export type InputTuple = [
    sequence: BigNumberish,
    account: string,
    destination: string,
    amount: BigNumberish,
    fee: BigNumberish,
    paymentReference: BytesLike
  ];
  export type OutputTuple = [
    sequence: bigint,
    account: string,
    destination: string,
    amount: bigint,
    fee: bigint,
    paymentReference: string
  ];
  export interface OutputObject {
    sequence: bigint;
    account: string;
    destination: string;
    amount: bigint;
    fee: bigint;
    paymentReference: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PreimageHashAddedEvent {
  export type InputTuple = [preimageHash: BytesLike];
  export type OutputTuple = [preimageHash: string];
  export interface OutputObject {
    preimageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettingsUpdatedEvent {
  export type InputTuple = [
    escrowEndTimeSeconds: BigNumberish,
    escrowAmount: BigNumberish,
    minimalAmount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    escrowEndTimeSeconds: bigint,
    escrowAmount: bigint,
    minimalAmount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    escrowEndTimeSeconds: bigint;
    escrowAmount: bigint;
    minimalAmount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedGovernanceCallCanceledEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedGovernanceCallExecutedEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestCanceledEvent {
  export type InputTuple = [
    destinationAddress: string,
    paymentReference: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    destinationAddress: string,
    paymentReference: string,
    amount: bigint
  ];
  export interface OutputObject {
    destinationAddress: string;
    paymentReference: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestedEvent {
  export type InputTuple = [
    destinationAddress: string,
    paymentReference: BytesLike,
    amount: BigNumberish,
    cancelable: boolean
  ];
  export type OutputTuple = [
    destinationAddress: string,
    paymentReference: string,
    amount: bigint,
    cancelable: boolean
  ];
  export interface OutputObject {
    destinationAddress: string;
    paymentReference: string;
    amount: bigint;
    cancelable: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggeringAccountAddedEvent {
  export type InputTuple = [triggeringAccount: AddressLike];
  export type OutputTuple = [triggeringAccount: string];
  export interface OutputObject {
    triggeringAccount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggeringAccountRemovedEvent {
  export type InputTuple = [triggeringAccount: AddressLike];
  export type OutputTuple = [triggeringAccount: string];
  export interface OutputObject {
    triggeringAccount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnusedPreimageHashRemovedEvent {
  export type InputTuple = [preimageHash: BytesLike];
  export type OutputTuple = [preimageHash: string];
  export interface OutputObject {
    preimageHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoreVaultManager extends BaseContract {
  connect(runner?: ContractRunner | null): CoreVaultManager;
  waitForDeployment(): Promise<this>;

  interface: CoreVaultManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAllowedDestinationAddresses: TypedContractMethod<
    [_allowedDestinationAddresses: string[]],
    [void],
    "nonpayable"
  >;

  addEmergencyPauseSenders: TypedContractMethod<
    [_addresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  addPreimageHashes: TypedContractMethod<
    [_preimageHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  addTriggeringAccounts: TypedContractMethod<
    [_triggeringAccounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  assetManager: TypedContractMethod<[], [string], "view">;

  availableFunds: TypedContractMethod<[], [bigint], "view">;

  cancelGovernanceCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelTransferRequestFromCoreVault: TypedContractMethod<
    [_destinationAddress: string],
    [void],
    "nonpayable"
  >;

  chainId: TypedContractMethod<[], [string], "view">;

  confirmPayment: TypedContractMethod<
    [_proof: IPayment.ProofStruct],
    [void],
    "nonpayable"
  >;

  confirmedPayments: TypedContractMethod<
    [transactionId: BytesLike],
    [boolean],
    "view"
  >;

  coreVaultAddress: TypedContractMethod<[], [string], "view">;

  coreVaultAddressHash: TypedContractMethod<[], [string], "view">;

  custodianAddress: TypedContractMethod<[], [string], "view">;

  escrowedFunds: TypedContractMethod<[], [bigint], "view">;

  executeGovernanceCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  fdcVerification: TypedContractMethod<[], [string], "view">;

  getAddressUpdater: TypedContractMethod<[], [string], "view">;

  getAllowedDestinationAddresses: TypedContractMethod<[], [string[]], "view">;

  getCancelableTransferRequests: TypedContractMethod<
    [],
    [ICoreVaultManager.TransferRequestStructOutput[]],
    "view"
  >;

  getEmergencyPauseSenders: TypedContractMethod<[], [string[]], "view">;

  getEscrowByIndex: TypedContractMethod<
    [_index: BigNumberish],
    [ICoreVaultManager.EscrowStructOutput],
    "view"
  >;

  getEscrowByPreimageHash: TypedContractMethod<
    [_preimageHash: BytesLike],
    [ICoreVaultManager.EscrowStructOutput],
    "view"
  >;

  getEscrowsCount: TypedContractMethod<[], [bigint], "view">;

  getNonCancelableTransferRequests: TypedContractMethod<
    [],
    [ICoreVaultManager.TransferRequestStructOutput[]],
    "view"
  >;

  getPreimageHash: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getPreimageHashesCount: TypedContractMethod<[], [bigint], "view">;

  getSettings: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _escrowEndTimeSeconds: bigint;
        _escrowAmount: bigint;
        _minimalAmount: bigint;
        _fee: bigint;
      }
    ],
    "view"
  >;

  getTriggeringAccounts: TypedContractMethod<[], [string[]], "view">;

  getUnprocessedEscrows: TypedContractMethod<
    [],
    [ICoreVaultManager.EscrowStructOutput[]],
    "view"
  >;

  getUnusedPreimageHashes: TypedContractMethod<[], [string[]], "view">;

  governance: TypedContractMethod<[], [string], "view">;

  governanceSettings: TypedContractMethod<[], [string], "view">;

  initialise: TypedContractMethod<
    [_governanceSettings: AddressLike, _initialGovernance: AddressLike],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      _governanceSettings: AddressLike,
      _initialGovernance: AddressLike,
      _addressUpdater: AddressLike,
      _assetManager: AddressLike,
      _chainId: BytesLike,
      _custodianAddress: string,
      _coreVaultAddress: string,
      _nextSequenceNumber: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isDestinationAddressAllowed: TypedContractMethod<
    [_address: string],
    [boolean],
    "view"
  >;

  isExecutor: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  nextSequenceNumber: TypedContractMethod<[], [bigint], "view">;

  nextUnprocessedEscrowIndex: TypedContractMethod<[], [bigint], "view">;

  nextUnusedPreimageHashIndex: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processEscrows: TypedContractMethod<
    [_maxCount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  productionMode: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeAllowedDestinationAddresses: TypedContractMethod<
    [_allowedDestinationAddresses: string[]],
    [void],
    "nonpayable"
  >;

  removeEmergencyPauseSenders: TypedContractMethod<
    [_addresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  removeTriggeringAccounts: TypedContractMethod<
    [_triggeringAccounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  removeUnusedPreimageHashes: TypedContractMethod<
    [_maxCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestTransferFromCoreVault: TypedContractMethod<
    [
      _destinationAddress: string,
      _paymentReference: BytesLike,
      _amount: BigNumberish,
      _cancelable: boolean
    ],
    [string],
    "nonpayable"
  >;

  setEscrowsFinished: TypedContractMethod<
    [_preimageHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [_interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  switchToProductionMode: TypedContractMethod<[], [void], "nonpayable">;

  totalRequestAmountWithFee: TypedContractMethod<[], [bigint], "view">;

  triggerCustomInstructions: TypedContractMethod<
    [_instructionsHash: BytesLike],
    [void],
    "nonpayable"
  >;

  triggerInstructions: TypedContractMethod<[], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateContractAddresses: TypedContractMethod<
    [_contractNameHashes: BytesLike[], _contractAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  updateCustodianAddress: TypedContractMethod<
    [_custodianAddress: string],
    [void],
    "nonpayable"
  >;

  updateSettings: TypedContractMethod<
    [
      _escrowEndTimeSeconds: BigNumberish,
      _escrowAmount: BigNumberish,
      _minimalAmount: BigNumberish,
      _fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAllowedDestinationAddresses"
  ): TypedContractMethod<
    [_allowedDestinationAddresses: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addEmergencyPauseSenders"
  ): TypedContractMethod<[_addresses: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPreimageHashes"
  ): TypedContractMethod<[_preimageHashes: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addTriggeringAccounts"
  ): TypedContractMethod<
    [_triggeringAccounts: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assetManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "availableFunds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelGovernanceCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTransferRequestFromCoreVault"
  ): TypedContractMethod<[_destinationAddress: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "chainId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confirmPayment"
  ): TypedContractMethod<[_proof: IPayment.ProofStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmedPayments"
  ): TypedContractMethod<[transactionId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "coreVaultAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "coreVaultAddressHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "custodianAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrowedFunds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeGovernanceCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fdcVerification"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAddressUpdater"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllowedDestinationAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCancelableTransferRequests"
  ): TypedContractMethod<
    [],
    [ICoreVaultManager.TransferRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEmergencyPauseSenders"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEscrowByIndex"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [ICoreVaultManager.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrowByPreimageHash"
  ): TypedContractMethod<
    [_preimageHash: BytesLike],
    [ICoreVaultManager.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrowsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNonCancelableTransferRequests"
  ): TypedContractMethod<
    [],
    [ICoreVaultManager.TransferRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPreimageHash"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPreimageHashesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSettings"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _escrowEndTimeSeconds: bigint;
        _escrowAmount: bigint;
        _minimalAmount: bigint;
        _fee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTriggeringAccounts"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUnprocessedEscrows"
  ): TypedContractMethod<[], [ICoreVaultManager.EscrowStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getUnusedPreimageHashes"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "governanceSettings"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialise"
  ): TypedContractMethod<
    [_governanceSettings: AddressLike, _initialGovernance: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _governanceSettings: AddressLike,
      _initialGovernance: AddressLike,
      _addressUpdater: AddressLike,
      _assetManager: AddressLike,
      _chainId: BytesLike,
      _custodianAddress: string,
      _coreVaultAddress: string,
      _nextSequenceNumber: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDestinationAddressAllowed"
  ): TypedContractMethod<[_address: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isExecutor"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextSequenceNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextUnprocessedEscrowIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextUnusedPreimageHashIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processEscrows"
  ): TypedContractMethod<[_maxCount: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "productionMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAllowedDestinationAddresses"
  ): TypedContractMethod<
    [_allowedDestinationAddresses: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeEmergencyPauseSenders"
  ): TypedContractMethod<[_addresses: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeTriggeringAccounts"
  ): TypedContractMethod<
    [_triggeringAccounts: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeUnusedPreimageHashes"
  ): TypedContractMethod<[_maxCount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestTransferFromCoreVault"
  ): TypedContractMethod<
    [
      _destinationAddress: string,
      _paymentReference: BytesLike,
      _amount: BigNumberish,
      _cancelable: boolean
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEscrowsFinished"
  ): TypedContractMethod<[_preimageHashes: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[_interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "switchToProductionMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalRequestAmountWithFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "triggerCustomInstructions"
  ): TypedContractMethod<[_instructionsHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerInstructions"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateContractAddresses"
  ): TypedContractMethod<
    [_contractNameHashes: BytesLike[], _contractAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCustodianAddress"
  ): TypedContractMethod<[_custodianAddress: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSettings"
  ): TypedContractMethod<
    [
      _escrowEndTimeSeconds: BigNumberish,
      _escrowAmount: BigNumberish,
      _minimalAmount: BigNumberish,
      _fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "AllowedDestinationAddressAdded"
  ): TypedContractEvent<
    AllowedDestinationAddressAddedEvent.InputTuple,
    AllowedDestinationAddressAddedEvent.OutputTuple,
    AllowedDestinationAddressAddedEvent.OutputObject
  >;
  getEvent(
    key: "AllowedDestinationAddressRemoved"
  ): TypedContractEvent<
    AllowedDestinationAddressRemovedEvent.InputTuple,
    AllowedDestinationAddressRemovedEvent.OutputTuple,
    AllowedDestinationAddressRemovedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "CustodianAddressUpdated"
  ): TypedContractEvent<
    CustodianAddressUpdatedEvent.InputTuple,
    CustodianAddressUpdatedEvent.OutputTuple,
    CustodianAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CustomInstructions"
  ): TypedContractEvent<
    CustomInstructionsEvent.InputTuple,
    CustomInstructionsEvent.OutputTuple,
    CustomInstructionsEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPauseSenderAdded"
  ): TypedContractEvent<
    EmergencyPauseSenderAddedEvent.InputTuple,
    EmergencyPauseSenderAddedEvent.OutputTuple,
    EmergencyPauseSenderAddedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPauseSenderRemoved"
  ): TypedContractEvent<
    EmergencyPauseSenderRemovedEvent.InputTuple,
    EmergencyPauseSenderRemovedEvent.OutputTuple,
    EmergencyPauseSenderRemovedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFinished"
  ): TypedContractEvent<
    EscrowFinishedEvent.InputTuple,
    EscrowFinishedEvent.OutputTuple,
    EscrowFinishedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowInstructions"
  ): TypedContractEvent<
    EscrowInstructionsEvent.InputTuple,
    EscrowInstructionsEvent.OutputTuple,
    EscrowInstructionsEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceCallTimelocked"
  ): TypedContractEvent<
    GovernanceCallTimelockedEvent.InputTuple,
    GovernanceCallTimelockedEvent.OutputTuple,
    GovernanceCallTimelockedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceInitialised"
  ): TypedContractEvent<
    GovernanceInitialisedEvent.InputTuple,
    GovernanceInitialisedEvent.OutputTuple,
    GovernanceInitialisedEvent.OutputObject
  >;
  getEvent(
    key: "GovernedProductionModeEntered"
  ): TypedContractEvent<
    GovernedProductionModeEnteredEvent.InputTuple,
    GovernedProductionModeEnteredEvent.OutputTuple,
    GovernedProductionModeEnteredEvent.OutputObject
  >;
  getEvent(
    key: "NotAllEscrowsProcessed"
  ): TypedContractEvent<
    NotAllEscrowsProcessedEvent.InputTuple,
    NotAllEscrowsProcessedEvent.OutputTuple,
    NotAllEscrowsProcessedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentConfirmed"
  ): TypedContractEvent<
    PaymentConfirmedEvent.InputTuple,
    PaymentConfirmedEvent.OutputTuple,
    PaymentConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentInstructions"
  ): TypedContractEvent<
    PaymentInstructionsEvent.InputTuple,
    PaymentInstructionsEvent.OutputTuple,
    PaymentInstructionsEvent.OutputObject
  >;
  getEvent(
    key: "PreimageHashAdded"
  ): TypedContractEvent<
    PreimageHashAddedEvent.InputTuple,
    PreimageHashAddedEvent.OutputTuple,
    PreimageHashAddedEvent.OutputObject
  >;
  getEvent(
    key: "SettingsUpdated"
  ): TypedContractEvent<
    SettingsUpdatedEvent.InputTuple,
    SettingsUpdatedEvent.OutputTuple,
    SettingsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedGovernanceCallCanceled"
  ): TypedContractEvent<
    TimelockedGovernanceCallCanceledEvent.InputTuple,
    TimelockedGovernanceCallCanceledEvent.OutputTuple,
    TimelockedGovernanceCallCanceledEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedGovernanceCallExecuted"
  ): TypedContractEvent<
    TimelockedGovernanceCallExecutedEvent.InputTuple,
    TimelockedGovernanceCallExecutedEvent.OutputTuple,
    TimelockedGovernanceCallExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequestCanceled"
  ): TypedContractEvent<
    TransferRequestCanceledEvent.InputTuple,
    TransferRequestCanceledEvent.OutputTuple,
    TransferRequestCanceledEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequested"
  ): TypedContractEvent<
    TransferRequestedEvent.InputTuple,
    TransferRequestedEvent.OutputTuple,
    TransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TriggeringAccountAdded"
  ): TypedContractEvent<
    TriggeringAccountAddedEvent.InputTuple,
    TriggeringAccountAddedEvent.OutputTuple,
    TriggeringAccountAddedEvent.OutputObject
  >;
  getEvent(
    key: "TriggeringAccountRemoved"
  ): TypedContractEvent<
    TriggeringAccountRemovedEvent.InputTuple,
    TriggeringAccountRemovedEvent.OutputTuple,
    TriggeringAccountRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UnusedPreimageHashRemoved"
  ): TypedContractEvent<
    UnusedPreimageHashRemovedEvent.InputTuple,
    UnusedPreimageHashRemovedEvent.OutputTuple,
    UnusedPreimageHashRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "AllowedDestinationAddressAdded(string)": TypedContractEvent<
      AllowedDestinationAddressAddedEvent.InputTuple,
      AllowedDestinationAddressAddedEvent.OutputTuple,
      AllowedDestinationAddressAddedEvent.OutputObject
    >;
    AllowedDestinationAddressAdded: TypedContractEvent<
      AllowedDestinationAddressAddedEvent.InputTuple,
      AllowedDestinationAddressAddedEvent.OutputTuple,
      AllowedDestinationAddressAddedEvent.OutputObject
    >;

    "AllowedDestinationAddressRemoved(string)": TypedContractEvent<
      AllowedDestinationAddressRemovedEvent.InputTuple,
      AllowedDestinationAddressRemovedEvent.OutputTuple,
      AllowedDestinationAddressRemovedEvent.OutputObject
    >;
    AllowedDestinationAddressRemoved: TypedContractEvent<
      AllowedDestinationAddressRemovedEvent.InputTuple,
      AllowedDestinationAddressRemovedEvent.OutputTuple,
      AllowedDestinationAddressRemovedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "CustodianAddressUpdated(string)": TypedContractEvent<
      CustodianAddressUpdatedEvent.InputTuple,
      CustodianAddressUpdatedEvent.OutputTuple,
      CustodianAddressUpdatedEvent.OutputObject
    >;
    CustodianAddressUpdated: TypedContractEvent<
      CustodianAddressUpdatedEvent.InputTuple,
      CustodianAddressUpdatedEvent.OutputTuple,
      CustodianAddressUpdatedEvent.OutputObject
    >;

    "CustomInstructions(uint256,string,bytes32)": TypedContractEvent<
      CustomInstructionsEvent.InputTuple,
      CustomInstructionsEvent.OutputTuple,
      CustomInstructionsEvent.OutputObject
    >;
    CustomInstructions: TypedContractEvent<
      CustomInstructionsEvent.InputTuple,
      CustomInstructionsEvent.OutputTuple,
      CustomInstructionsEvent.OutputObject
    >;

    "EmergencyPauseSenderAdded(address)": TypedContractEvent<
      EmergencyPauseSenderAddedEvent.InputTuple,
      EmergencyPauseSenderAddedEvent.OutputTuple,
      EmergencyPauseSenderAddedEvent.OutputObject
    >;
    EmergencyPauseSenderAdded: TypedContractEvent<
      EmergencyPauseSenderAddedEvent.InputTuple,
      EmergencyPauseSenderAddedEvent.OutputTuple,
      EmergencyPauseSenderAddedEvent.OutputObject
    >;

    "EmergencyPauseSenderRemoved(address)": TypedContractEvent<
      EmergencyPauseSenderRemovedEvent.InputTuple,
      EmergencyPauseSenderRemovedEvent.OutputTuple,
      EmergencyPauseSenderRemovedEvent.OutputObject
    >;
    EmergencyPauseSenderRemoved: TypedContractEvent<
      EmergencyPauseSenderRemovedEvent.InputTuple,
      EmergencyPauseSenderRemovedEvent.OutputTuple,
      EmergencyPauseSenderRemovedEvent.OutputObject
    >;

    "EscrowFinished(bytes32,uint256)": TypedContractEvent<
      EscrowFinishedEvent.InputTuple,
      EscrowFinishedEvent.OutputTuple,
      EscrowFinishedEvent.OutputObject
    >;
    EscrowFinished: TypedContractEvent<
      EscrowFinishedEvent.InputTuple,
      EscrowFinishedEvent.OutputTuple,
      EscrowFinishedEvent.OutputObject
    >;

    "EscrowInstructions(uint256,bytes32,string,string,uint256,uint256,uint256)": TypedContractEvent<
      EscrowInstructionsEvent.InputTuple,
      EscrowInstructionsEvent.OutputTuple,
      EscrowInstructionsEvent.OutputObject
    >;
    EscrowInstructions: TypedContractEvent<
      EscrowInstructionsEvent.InputTuple,
      EscrowInstructionsEvent.OutputTuple,
      EscrowInstructionsEvent.OutputObject
    >;

    "GovernanceCallTimelocked(bytes,bytes32,uint256)": TypedContractEvent<
      GovernanceCallTimelockedEvent.InputTuple,
      GovernanceCallTimelockedEvent.OutputTuple,
      GovernanceCallTimelockedEvent.OutputObject
    >;
    GovernanceCallTimelocked: TypedContractEvent<
      GovernanceCallTimelockedEvent.InputTuple,
      GovernanceCallTimelockedEvent.OutputTuple,
      GovernanceCallTimelockedEvent.OutputObject
    >;

    "GovernanceInitialised(address)": TypedContractEvent<
      GovernanceInitialisedEvent.InputTuple,
      GovernanceInitialisedEvent.OutputTuple,
      GovernanceInitialisedEvent.OutputObject
    >;
    GovernanceInitialised: TypedContractEvent<
      GovernanceInitialisedEvent.InputTuple,
      GovernanceInitialisedEvent.OutputTuple,
      GovernanceInitialisedEvent.OutputObject
    >;

    "GovernedProductionModeEntered(address)": TypedContractEvent<
      GovernedProductionModeEnteredEvent.InputTuple,
      GovernedProductionModeEnteredEvent.OutputTuple,
      GovernedProductionModeEnteredEvent.OutputObject
    >;
    GovernedProductionModeEntered: TypedContractEvent<
      GovernedProductionModeEnteredEvent.InputTuple,
      GovernedProductionModeEnteredEvent.OutputTuple,
      GovernedProductionModeEnteredEvent.OutputObject
    >;

    "NotAllEscrowsProcessed()": TypedContractEvent<
      NotAllEscrowsProcessedEvent.InputTuple,
      NotAllEscrowsProcessedEvent.OutputTuple,
      NotAllEscrowsProcessedEvent.OutputObject
    >;
    NotAllEscrowsProcessed: TypedContractEvent<
      NotAllEscrowsProcessedEvent.InputTuple,
      NotAllEscrowsProcessedEvent.OutputTuple,
      NotAllEscrowsProcessedEvent.OutputObject
    >;

    "Paused()": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentConfirmed(bytes32,bytes32,uint256)": TypedContractEvent<
      PaymentConfirmedEvent.InputTuple,
      PaymentConfirmedEvent.OutputTuple,
      PaymentConfirmedEvent.OutputObject
    >;
    PaymentConfirmed: TypedContractEvent<
      PaymentConfirmedEvent.InputTuple,
      PaymentConfirmedEvent.OutputTuple,
      PaymentConfirmedEvent.OutputObject
    >;

    "PaymentInstructions(uint256,string,string,uint256,uint256,bytes32)": TypedContractEvent<
      PaymentInstructionsEvent.InputTuple,
      PaymentInstructionsEvent.OutputTuple,
      PaymentInstructionsEvent.OutputObject
    >;
    PaymentInstructions: TypedContractEvent<
      PaymentInstructionsEvent.InputTuple,
      PaymentInstructionsEvent.OutputTuple,
      PaymentInstructionsEvent.OutputObject
    >;

    "PreimageHashAdded(bytes32)": TypedContractEvent<
      PreimageHashAddedEvent.InputTuple,
      PreimageHashAddedEvent.OutputTuple,
      PreimageHashAddedEvent.OutputObject
    >;
    PreimageHashAdded: TypedContractEvent<
      PreimageHashAddedEvent.InputTuple,
      PreimageHashAddedEvent.OutputTuple,
      PreimageHashAddedEvent.OutputObject
    >;

    "SettingsUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      SettingsUpdatedEvent.InputTuple,
      SettingsUpdatedEvent.OutputTuple,
      SettingsUpdatedEvent.OutputObject
    >;
    SettingsUpdated: TypedContractEvent<
      SettingsUpdatedEvent.InputTuple,
      SettingsUpdatedEvent.OutputTuple,
      SettingsUpdatedEvent.OutputObject
    >;

    "TimelockedGovernanceCallCanceled(bytes32)": TypedContractEvent<
      TimelockedGovernanceCallCanceledEvent.InputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputObject
    >;
    TimelockedGovernanceCallCanceled: TypedContractEvent<
      TimelockedGovernanceCallCanceledEvent.InputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputObject
    >;

    "TimelockedGovernanceCallExecuted(bytes32)": TypedContractEvent<
      TimelockedGovernanceCallExecutedEvent.InputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputObject
    >;
    TimelockedGovernanceCallExecuted: TypedContractEvent<
      TimelockedGovernanceCallExecutedEvent.InputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputObject
    >;

    "TransferRequestCanceled(string,bytes32,uint256)": TypedContractEvent<
      TransferRequestCanceledEvent.InputTuple,
      TransferRequestCanceledEvent.OutputTuple,
      TransferRequestCanceledEvent.OutputObject
    >;
    TransferRequestCanceled: TypedContractEvent<
      TransferRequestCanceledEvent.InputTuple,
      TransferRequestCanceledEvent.OutputTuple,
      TransferRequestCanceledEvent.OutputObject
    >;

    "TransferRequested(string,bytes32,uint256,bool)": TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
    TransferRequested: TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;

    "TriggeringAccountAdded(address)": TypedContractEvent<
      TriggeringAccountAddedEvent.InputTuple,
      TriggeringAccountAddedEvent.OutputTuple,
      TriggeringAccountAddedEvent.OutputObject
    >;
    TriggeringAccountAdded: TypedContractEvent<
      TriggeringAccountAddedEvent.InputTuple,
      TriggeringAccountAddedEvent.OutputTuple,
      TriggeringAccountAddedEvent.OutputObject
    >;

    "TriggeringAccountRemoved(address)": TypedContractEvent<
      TriggeringAccountRemovedEvent.InputTuple,
      TriggeringAccountRemovedEvent.OutputTuple,
      TriggeringAccountRemovedEvent.OutputObject
    >;
    TriggeringAccountRemoved: TypedContractEvent<
      TriggeringAccountRemovedEvent.InputTuple,
      TriggeringAccountRemovedEvent.OutputTuple,
      TriggeringAccountRemovedEvent.OutputObject
    >;

    "Unpaused()": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UnusedPreimageHashRemoved(bytes32)": TypedContractEvent<
      UnusedPreimageHashRemovedEvent.InputTuple,
      UnusedPreimageHashRemovedEvent.OutputTuple,
      UnusedPreimageHashRemovedEvent.OutputObject
    >;
    UnusedPreimageHashRemoved: TypedContractEvent<
      UnusedPreimageHashRemovedEvent.InputTuple,
      UnusedPreimageHashRemovedEvent.OutputTuple,
      UnusedPreimageHashRemovedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
