/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FtsoV2PriceStore__factory } from "./FtsoV2PriceStore__factory";
export { FtsoV2PriceStoreProxy__factory } from "./FtsoV2PriceStoreProxy__factory";
