version: '3.8'
services:
  # PostgreSQL Service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: executor_minting_redemptions
      POSTGRES_USER: executor
      POSTGRES_PASSWORD: executor
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
       #- /var/lib/postgresql/data
      #- postgres_data:/var/lib/postgresql/data

  # Application Service
  app:
    image: demodapp
    build: .
    command: ["yarn", "run", "start"]
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    depends_on:
      - postgres

volumes:
  postgres_data: