/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Governed } from "./Governed";
export type { GovernedBase } from "./GovernedBase";
export type { GovernedProxyImplementation } from "./GovernedProxyImplementation";
export type { GovernedUUPSProxyImplementation } from "./GovernedUUPSProxyImplementation";
