/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IAssetManagerEvents {
  export type AgentVaultCreationDataStruct = {
    collateralPool: AddressLike;
    collateralPoolToken: AddressLike;
    underlyingAddress: string;
    vaultCollateralToken: AddressLike;
    poolWNatToken: AddressLike;
    feeBIPS: BigNumberish;
    poolFeeShareBIPS: BigNumberish;
    mintingVaultCollateralRatioBIPS: BigNumberish;
    mintingPoolCollateralRatioBIPS: BigNumberish;
    buyFAssetByAgentFactorBIPS: BigNumberish;
    poolExitCollateralRatioBIPS: BigNumberish;
    redemptionPoolFeeShareBIPS: BigNumberish;
  };

  export type AgentVaultCreationDataStructOutput = [
    collateralPool: string,
    collateralPoolToken: string,
    underlyingAddress: string,
    vaultCollateralToken: string,
    poolWNatToken: string,
    feeBIPS: bigint,
    poolFeeShareBIPS: bigint,
    mintingVaultCollateralRatioBIPS: bigint,
    mintingPoolCollateralRatioBIPS: bigint,
    buyFAssetByAgentFactorBIPS: bigint,
    poolExitCollateralRatioBIPS: bigint,
    redemptionPoolFeeShareBIPS: bigint
  ] & {
    collateralPool: string;
    collateralPoolToken: string;
    underlyingAddress: string;
    vaultCollateralToken: string;
    poolWNatToken: string;
    feeBIPS: bigint;
    poolFeeShareBIPS: bigint;
    mintingVaultCollateralRatioBIPS: bigint;
    mintingPoolCollateralRatioBIPS: bigint;
    buyFAssetByAgentFactorBIPS: bigint;
    poolExitCollateralRatioBIPS: bigint;
    redemptionPoolFeeShareBIPS: bigint;
  };
}

export declare namespace IAddressValidity {
  export type RequestBodyStruct = { addressStr: string };

  export type RequestBodyStructOutput = [addressStr: string] & {
    addressStr: string;
  };

  export type ResponseBodyStruct = {
    isValid: boolean;
    standardAddress: string;
    standardAddressHash: BytesLike;
  };

  export type ResponseBodyStructOutput = [
    isValid: boolean,
    standardAddress: string,
    standardAddressHash: string
  ] & {
    isValid: boolean;
    standardAddress: string;
    standardAddressHash: string;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IAddressValidity.RequestBodyStruct;
    responseBody: IAddressValidity.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IAddressValidity.RequestBodyStructOutput,
    responseBody: IAddressValidity.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IAddressValidity.RequestBodyStructOutput;
    responseBody: IAddressValidity.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IAddressValidity.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IAddressValidity.ResponseStructOutput
  ] & { merkleProof: string[]; data: IAddressValidity.ResponseStructOutput };
}

export declare namespace AgentSettings {
  export type DataStruct = {
    vaultCollateralToken: AddressLike;
    poolTokenSuffix: string;
    feeBIPS: BigNumberish;
    poolFeeShareBIPS: BigNumberish;
    mintingVaultCollateralRatioBIPS: BigNumberish;
    mintingPoolCollateralRatioBIPS: BigNumberish;
    buyFAssetByAgentFactorBIPS: BigNumberish;
    poolExitCollateralRatioBIPS: BigNumberish;
    redemptionPoolFeeShareBIPS: BigNumberish;
  };

  export type DataStructOutput = [
    vaultCollateralToken: string,
    poolTokenSuffix: string,
    feeBIPS: bigint,
    poolFeeShareBIPS: bigint,
    mintingVaultCollateralRatioBIPS: bigint,
    mintingPoolCollateralRatioBIPS: bigint,
    buyFAssetByAgentFactorBIPS: bigint,
    poolExitCollateralRatioBIPS: bigint,
    redemptionPoolFeeShareBIPS: bigint
  ] & {
    vaultCollateralToken: string;
    poolTokenSuffix: string;
    feeBIPS: bigint;
    poolFeeShareBIPS: bigint;
    mintingVaultCollateralRatioBIPS: bigint;
    mintingPoolCollateralRatioBIPS: bigint;
    buyFAssetByAgentFactorBIPS: bigint;
    poolExitCollateralRatioBIPS: bigint;
    redemptionPoolFeeShareBIPS: bigint;
  };
}

export interface AgentVaultManagementFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "announceDestroyAgent"
      | "createAgentVault"
      | "destroyAgent"
      | "upgradeAgentVaultAndPool"
      | "upgradeAgentVaultsAndPools"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDestroyAnnounced"
      | "AgentDestroyed"
      | "AgentVaultCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "announceDestroyAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgentVault",
    values: [IAddressValidity.ProofStruct, AgentSettings.DataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "destroyAgent",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeAgentVaultAndPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeAgentVaultsAndPools",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "announceDestroyAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgentVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "destroyAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAgentVaultAndPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAgentVaultsAndPools",
    data: BytesLike
  ): Result;
}

export namespace AgentDestroyAnnouncedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    destroyAllowedAt: BigNumberish
  ];
  export type OutputTuple = [agentVault: string, destroyAllowedAt: bigint];
  export interface OutputObject {
    agentVault: string;
    destroyAllowedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentDestroyedEvent {
  export type InputTuple = [agentVault: AddressLike];
  export type OutputTuple = [agentVault: string];
  export interface OutputObject {
    agentVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentVaultCreatedEvent {
  export type InputTuple = [
    owner: AddressLike,
    agentVault: AddressLike,
    creationData: IAssetManagerEvents.AgentVaultCreationDataStruct
  ];
  export type OutputTuple = [
    owner: string,
    agentVault: string,
    creationData: IAssetManagerEvents.AgentVaultCreationDataStructOutput
  ];
  export interface OutputObject {
    owner: string;
    agentVault: string;
    creationData: IAssetManagerEvents.AgentVaultCreationDataStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentVaultManagementFacet extends BaseContract {
  connect(runner?: ContractRunner | null): AgentVaultManagementFacet;
  waitForDeployment(): Promise<this>;

  interface: AgentVaultManagementFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  announceDestroyAgent: TypedContractMethod<
    [_agentVault: AddressLike],
    [bigint],
    "nonpayable"
  >;

  createAgentVault: TypedContractMethod<
    [
      _addressProof: IAddressValidity.ProofStruct,
      _settings: AgentSettings.DataStruct
    ],
    [string],
    "nonpayable"
  >;

  destroyAgent: TypedContractMethod<
    [_agentVault: AddressLike, _recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeAgentVaultAndPool: TypedContractMethod<
    [_agentVault: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeAgentVaultsAndPools: TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "announceDestroyAgent"
  ): TypedContractMethod<[_agentVault: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createAgentVault"
  ): TypedContractMethod<
    [
      _addressProof: IAddressValidity.ProofStruct,
      _settings: AgentSettings.DataStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "destroyAgent"
  ): TypedContractMethod<
    [_agentVault: AddressLike, _recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeAgentVaultAndPool"
  ): TypedContractMethod<[_agentVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeAgentVaultsAndPools"
  ): TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentDestroyAnnounced"
  ): TypedContractEvent<
    AgentDestroyAnnouncedEvent.InputTuple,
    AgentDestroyAnnouncedEvent.OutputTuple,
    AgentDestroyAnnouncedEvent.OutputObject
  >;
  getEvent(
    key: "AgentDestroyed"
  ): TypedContractEvent<
    AgentDestroyedEvent.InputTuple,
    AgentDestroyedEvent.OutputTuple,
    AgentDestroyedEvent.OutputObject
  >;
  getEvent(
    key: "AgentVaultCreated"
  ): TypedContractEvent<
    AgentVaultCreatedEvent.InputTuple,
    AgentVaultCreatedEvent.OutputTuple,
    AgentVaultCreatedEvent.OutputObject
  >;

  filters: {
    "AgentDestroyAnnounced(address,uint256)": TypedContractEvent<
      AgentDestroyAnnouncedEvent.InputTuple,
      AgentDestroyAnnouncedEvent.OutputTuple,
      AgentDestroyAnnouncedEvent.OutputObject
    >;
    AgentDestroyAnnounced: TypedContractEvent<
      AgentDestroyAnnouncedEvent.InputTuple,
      AgentDestroyAnnouncedEvent.OutputTuple,
      AgentDestroyAnnouncedEvent.OutputObject
    >;

    "AgentDestroyed(address)": TypedContractEvent<
      AgentDestroyedEvent.InputTuple,
      AgentDestroyedEvent.OutputTuple,
      AgentDestroyedEvent.OutputObject
    >;
    AgentDestroyed: TypedContractEvent<
      AgentDestroyedEvent.InputTuple,
      AgentDestroyedEvent.OutputTuple,
      AgentDestroyedEvent.OutputObject
    >;

    "AgentVaultCreated(address,address,tuple)": TypedContractEvent<
      AgentVaultCreatedEvent.InputTuple,
      AgentVaultCreatedEvent.OutputTuple,
      AgentVaultCreatedEvent.OutputObject
    >;
    AgentVaultCreated: TypedContractEvent<
      AgentVaultCreatedEvent.InputTuple,
      AgentVaultCreatedEvent.OutputTuple,
      AgentVaultCreatedEvent.OutputObject
    >;
  };
}
