/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IBalanceDecreasingTransaction {
  export type RequestBodyStruct = {
    transactionId: BytesLike;
    sourceAddressIndicator: BytesLike;
  };

  export type RequestBodyStructOutput = [
    transactionId: string,
    sourceAddressIndicator: string
  ] & { transactionId: string; sourceAddressIndicator: string };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    blockTimestamp: BigNumberish;
    sourceAddressHash: BytesLike;
    spentAmount: BigNumberish;
    standardPaymentReference: BytesLike;
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    blockTimestamp: bigint,
    sourceAddressHash: string,
    spentAmount: bigint,
    standardPaymentReference: string
  ] & {
    blockNumber: bigint;
    blockTimestamp: bigint;
    sourceAddressHash: string;
    spentAmount: bigint;
    standardPaymentReference: string;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IBalanceDecreasingTransaction.RequestBodyStruct;
    responseBody: IBalanceDecreasingTransaction.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IBalanceDecreasingTransaction.RequestBodyStructOutput,
    responseBody: IBalanceDecreasingTransaction.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IBalanceDecreasingTransaction.RequestBodyStructOutput;
    responseBody: IBalanceDecreasingTransaction.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IBalanceDecreasingTransaction.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IBalanceDecreasingTransaction.ResponseStructOutput
  ] & {
    merkleProof: string[];
    data: IBalanceDecreasingTransaction.ResponseStructOutput;
  };
}

export interface ChallengesFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "doublePaymentChallenge"
      | "freeBalanceNegativeChallenge"
      | "illegalPaymentChallenge"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DuplicatePaymentConfirmed"
      | "FullLiquidationStarted"
      | "IllegalPaymentConfirmed"
      | "UnderlyingBalanceTooLow"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "doublePaymentChallenge",
    values: [
      IBalanceDecreasingTransaction.ProofStruct,
      IBalanceDecreasingTransaction.ProofStruct,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "freeBalanceNegativeChallenge",
    values: [IBalanceDecreasingTransaction.ProofStruct[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "illegalPaymentChallenge",
    values: [IBalanceDecreasingTransaction.ProofStruct, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "doublePaymentChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freeBalanceNegativeChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "illegalPaymentChallenge",
    data: BytesLike
  ): Result;
}

export namespace DuplicatePaymentConfirmedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    transactionHash1: BytesLike,
    transactionHash2: BytesLike
  ];
  export type OutputTuple = [
    agentVault: string,
    transactionHash1: string,
    transactionHash2: string
  ];
  export interface OutputObject {
    agentVault: string;
    transactionHash1: string;
    transactionHash2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FullLiquidationStartedEvent {
  export type InputTuple = [agentVault: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agentVault: string, timestamp: bigint];
  export interface OutputObject {
    agentVault: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IllegalPaymentConfirmedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    transactionHash: BytesLike
  ];
  export type OutputTuple = [agentVault: string, transactionHash: string];
  export interface OutputObject {
    agentVault: string;
    transactionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnderlyingBalanceTooLowEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    balance: BigNumberish,
    requiredBalance: BigNumberish
  ];
  export type OutputTuple = [
    agentVault: string,
    balance: bigint,
    requiredBalance: bigint
  ];
  export interface OutputObject {
    agentVault: string;
    balance: bigint;
    requiredBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChallengesFacet extends BaseContract {
  connect(runner?: ContractRunner | null): ChallengesFacet;
  waitForDeployment(): Promise<this>;

  interface: ChallengesFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  doublePaymentChallenge: TypedContractMethod<
    [
      _payment1: IBalanceDecreasingTransaction.ProofStruct,
      _payment2: IBalanceDecreasingTransaction.ProofStruct,
      _agentVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  freeBalanceNegativeChallenge: TypedContractMethod<
    [
      _payments: IBalanceDecreasingTransaction.ProofStruct[],
      _agentVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  illegalPaymentChallenge: TypedContractMethod<
    [
      _payment: IBalanceDecreasingTransaction.ProofStruct,
      _agentVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "doublePaymentChallenge"
  ): TypedContractMethod<
    [
      _payment1: IBalanceDecreasingTransaction.ProofStruct,
      _payment2: IBalanceDecreasingTransaction.ProofStruct,
      _agentVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freeBalanceNegativeChallenge"
  ): TypedContractMethod<
    [
      _payments: IBalanceDecreasingTransaction.ProofStruct[],
      _agentVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "illegalPaymentChallenge"
  ): TypedContractMethod<
    [
      _payment: IBalanceDecreasingTransaction.ProofStruct,
      _agentVault: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DuplicatePaymentConfirmed"
  ): TypedContractEvent<
    DuplicatePaymentConfirmedEvent.InputTuple,
    DuplicatePaymentConfirmedEvent.OutputTuple,
    DuplicatePaymentConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "FullLiquidationStarted"
  ): TypedContractEvent<
    FullLiquidationStartedEvent.InputTuple,
    FullLiquidationStartedEvent.OutputTuple,
    FullLiquidationStartedEvent.OutputObject
  >;
  getEvent(
    key: "IllegalPaymentConfirmed"
  ): TypedContractEvent<
    IllegalPaymentConfirmedEvent.InputTuple,
    IllegalPaymentConfirmedEvent.OutputTuple,
    IllegalPaymentConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "UnderlyingBalanceTooLow"
  ): TypedContractEvent<
    UnderlyingBalanceTooLowEvent.InputTuple,
    UnderlyingBalanceTooLowEvent.OutputTuple,
    UnderlyingBalanceTooLowEvent.OutputObject
  >;

  filters: {
    "DuplicatePaymentConfirmed(address,bytes32,bytes32)": TypedContractEvent<
      DuplicatePaymentConfirmedEvent.InputTuple,
      DuplicatePaymentConfirmedEvent.OutputTuple,
      DuplicatePaymentConfirmedEvent.OutputObject
    >;
    DuplicatePaymentConfirmed: TypedContractEvent<
      DuplicatePaymentConfirmedEvent.InputTuple,
      DuplicatePaymentConfirmedEvent.OutputTuple,
      DuplicatePaymentConfirmedEvent.OutputObject
    >;

    "FullLiquidationStarted(address,uint256)": TypedContractEvent<
      FullLiquidationStartedEvent.InputTuple,
      FullLiquidationStartedEvent.OutputTuple,
      FullLiquidationStartedEvent.OutputObject
    >;
    FullLiquidationStarted: TypedContractEvent<
      FullLiquidationStartedEvent.InputTuple,
      FullLiquidationStartedEvent.OutputTuple,
      FullLiquidationStartedEvent.OutputObject
    >;

    "IllegalPaymentConfirmed(address,bytes32)": TypedContractEvent<
      IllegalPaymentConfirmedEvent.InputTuple,
      IllegalPaymentConfirmedEvent.OutputTuple,
      IllegalPaymentConfirmedEvent.OutputObject
    >;
    IllegalPaymentConfirmed: TypedContractEvent<
      IllegalPaymentConfirmedEvent.InputTuple,
      IllegalPaymentConfirmedEvent.OutputTuple,
      IllegalPaymentConfirmedEvent.OutputObject
    >;

    "UnderlyingBalanceTooLow(address,int256,uint256)": TypedContractEvent<
      UnderlyingBalanceTooLowEvent.InputTuple,
      UnderlyingBalanceTooLowEvent.OutputTuple,
      UnderlyingBalanceTooLowEvent.OutputObject
    >;
    UnderlyingBalanceTooLow: TypedContractEvent<
      UnderlyingBalanceTooLowEvent.InputTuple,
      UnderlyingBalanceTooLowEvent.OutputTuple,
      UnderlyingBalanceTooLowEvent.OutputObject
    >;
  };
}
