/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface CollateralReservationsFacetInterface extends Interface {
  getFunction(
    nameOrSignature: "collateralReservationFee" | "reserveCollateral"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CollateralReserved"): EventFragment;

  encodeFunctionData(
    functionFragment: "collateralReservationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveCollateral",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "collateralReservationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveCollateral",
    data: BytesLike
  ): Result;
}

export namespace CollateralReservedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    minter: AddressLike,
    collateralReservationId: BigNumberish,
    valueUBA: BigNumberish,
    feeUBA: BigNumberish,
    firstUnderlyingBlock: BigNumberish,
    lastUnderlyingBlock: BigNumberish,
    lastUnderlyingTimestamp: BigNumberish,
    paymentAddress: string,
    paymentReference: BytesLike,
    executor: AddressLike,
    executorFeeNatWei: BigNumberish
  ];
  export type OutputTuple = [
    agentVault: string,
    minter: string,
    collateralReservationId: bigint,
    valueUBA: bigint,
    feeUBA: bigint,
    firstUnderlyingBlock: bigint,
    lastUnderlyingBlock: bigint,
    lastUnderlyingTimestamp: bigint,
    paymentAddress: string,
    paymentReference: string,
    executor: string,
    executorFeeNatWei: bigint
  ];
  export interface OutputObject {
    agentVault: string;
    minter: string;
    collateralReservationId: bigint;
    valueUBA: bigint;
    feeUBA: bigint;
    firstUnderlyingBlock: bigint;
    lastUnderlyingBlock: bigint;
    lastUnderlyingTimestamp: bigint;
    paymentAddress: string;
    paymentReference: string;
    executor: string;
    executorFeeNatWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CollateralReservationsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): CollateralReservationsFacet;
  waitForDeployment(): Promise<this>;

  interface: CollateralReservationsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  collateralReservationFee: TypedContractMethod<
    [_lots: BigNumberish],
    [bigint],
    "view"
  >;

  reserveCollateral: TypedContractMethod<
    [
      _agentVault: AddressLike,
      _lots: BigNumberish,
      _maxMintingFeeBIPS: BigNumberish,
      _executor: AddressLike
    ],
    [bigint],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "collateralReservationFee"
  ): TypedContractMethod<[_lots: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveCollateral"
  ): TypedContractMethod<
    [
      _agentVault: AddressLike,
      _lots: BigNumberish,
      _maxMintingFeeBIPS: BigNumberish,
      _executor: AddressLike
    ],
    [bigint],
    "payable"
  >;

  getEvent(
    key: "CollateralReserved"
  ): TypedContractEvent<
    CollateralReservedEvent.InputTuple,
    CollateralReservedEvent.OutputTuple,
    CollateralReservedEvent.OutputObject
  >;

  filters: {
    "CollateralReserved(address,address,uint256,uint256,uint256,uint256,uint256,uint256,string,bytes32,address,uint256)": TypedContractEvent<
      CollateralReservedEvent.InputTuple,
      CollateralReservedEvent.OutputTuple,
      CollateralReservedEvent.OutputObject
    >;
    CollateralReserved: TypedContractEvent<
      CollateralReservedEvent.InputTuple,
      CollateralReservedEvent.OutputTuple,
      CollateralReservedEvent.OutputObject
    >;
  };
}
