/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface DirectMintingSettingsFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelGovernanceCall"
      | "executeGovernanceCall"
      | "getDirectMintingDailyLimitUBA"
      | "getDirectMintingDailyLimiterState"
      | "getDirectMintingExecutorFeeUBA"
      | "getDirectMintingFeeBIPS"
      | "getDirectMintingFeeReceiver"
      | "getDirectMintingHourlyLimitUBA"
      | "getDirectMintingHourlyLimiterState"
      | "getDirectMintingLargeMintingDelaySeconds"
      | "getDirectMintingLargeMintingThresholdUBA"
      | "getDirectMintingMinimumFeeUBA"
      | "getDirectMintingOthersCanExecuteAfterSeconds"
      | "getDirectMintingsUnblockUntilTimestamp"
      | "getMintingTagManager"
      | "getSmartAccountManager"
      | "governance"
      | "governanceSettings"
      | "isExecutor"
      | "productionMode"
      | "setDirectMintingDailyLimitUBA"
      | "setDirectMintingExecutorFee"
      | "setDirectMintingFee"
      | "setDirectMintingFeeReceiver"
      | "setDirectMintingHourlyLimitUBA"
      | "setDirectMintingLargeMintingThrottling"
      | "setDirectMintingOthersCanExecuteAfterSeconds"
      | "setMintingTagManager"
      | "setSmartAccountManager"
      | "switchToProductionMode"
      | "unblockDirectMintingsUntil"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractChanged"
      | "DirectMintingsUnblocked"
      | "GovernanceCallTimelocked"
      | "GovernanceInitialised"
      | "GovernedProductionModeEntered"
      | "SettingChanged"
      | "TimelockedGovernanceCallCanceled"
      | "TimelockedGovernanceCallExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelGovernanceCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeGovernanceCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingDailyLimitUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingDailyLimiterState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingExecutorFeeUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingFeeBIPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingHourlyLimitUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingHourlyLimiterState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingLargeMintingDelaySeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingLargeMintingThresholdUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingMinimumFeeUBA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingOthersCanExecuteAfterSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectMintingsUnblockUntilTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMintingTagManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSmartAccountManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceSettings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "productionMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingDailyLimitUBA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingExecutorFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingFee",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingHourlyLimitUBA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingLargeMintingThrottling",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectMintingOthersCanExecuteAfterSeconds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingTagManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSmartAccountManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "switchToProductionMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unblockDirectMintingsUntil",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelGovernanceCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeGovernanceCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingDailyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingDailyLimiterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingExecutorFeeUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingFeeBIPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingHourlyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingHourlyLimiterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingLargeMintingDelaySeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingLargeMintingThresholdUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingMinimumFeeUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingOthersCanExecuteAfterSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDirectMintingsUnblockUntilTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintingTagManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmartAccountManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExecutor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productionMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingDailyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingExecutorFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingHourlyLimitUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingLargeMintingThrottling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDirectMintingOthersCanExecuteAfterSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingTagManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSmartAccountManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "switchToProductionMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockDirectMintingsUntil",
    data: BytesLike
  ): Result;
}

export namespace ContractChangedEvent {
  export type InputTuple = [name: string, value: AddressLike];
  export type OutputTuple = [name: string, value: string];
  export interface OutputObject {
    name: string;
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectMintingsUnblockedEvent {
  export type InputTuple = [startedUntilTimestamp: BigNumberish];
  export type OutputTuple = [startedUntilTimestamp: bigint];
  export interface OutputObject {
    startedUntilTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceCallTimelockedEvent {
  export type InputTuple = [
    encodedCall: BytesLike,
    encodedCallHash: BytesLike,
    allowedAfterTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    encodedCall: string,
    encodedCallHash: string,
    allowedAfterTimestamp: bigint
  ];
  export interface OutputObject {
    encodedCall: string;
    encodedCallHash: string;
    allowedAfterTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceInitialisedEvent {
  export type InputTuple = [initialGovernance: AddressLike];
  export type OutputTuple = [initialGovernance: string];
  export interface OutputObject {
    initialGovernance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernedProductionModeEnteredEvent {
  export type InputTuple = [governanceSettings: AddressLike];
  export type OutputTuple = [governanceSettings: string];
  export interface OutputObject {
    governanceSettings: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettingChangedEvent {
  export type InputTuple = [name: string, value: BigNumberish];
  export type OutputTuple = [name: string, value: bigint];
  export interface OutputObject {
    name: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedGovernanceCallCanceledEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedGovernanceCallExecutedEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DirectMintingSettingsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): DirectMintingSettingsFacet;
  waitForDeployment(): Promise<this>;

  interface: DirectMintingSettingsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelGovernanceCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  executeGovernanceCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  getDirectMintingDailyLimitUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingDailyLimiterState: TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;

  getDirectMintingExecutorFeeUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingFeeBIPS: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingFeeReceiver: TypedContractMethod<[], [string], "view">;

  getDirectMintingHourlyLimitUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingHourlyLimiterState: TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;

  getDirectMintingLargeMintingDelaySeconds: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getDirectMintingLargeMintingThresholdUBA: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getDirectMintingMinimumFeeUBA: TypedContractMethod<[], [bigint], "view">;

  getDirectMintingOthersCanExecuteAfterSeconds: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getDirectMintingsUnblockUntilTimestamp: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getMintingTagManager: TypedContractMethod<[], [string], "view">;

  getSmartAccountManager: TypedContractMethod<[], [string], "view">;

  governance: TypedContractMethod<[], [string], "view">;

  governanceSettings: TypedContractMethod<[], [string], "view">;

  isExecutor: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  productionMode: TypedContractMethod<[], [boolean], "view">;

  setDirectMintingDailyLimitUBA: TypedContractMethod<
    [_dailyLimitUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingExecutorFee: TypedContractMethod<
    [_executorFeeUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingFee: TypedContractMethod<
    [_mintingFeeBIPS: BigNumberish, _minimumMintingFeeUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingFeeReceiver: TypedContractMethod<
    [_mintingFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  setDirectMintingHourlyLimitUBA: TypedContractMethod<
    [_hourlyLimitUBA: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectMintingLargeMintingThrottling: TypedContractMethod<
    [
      _largeMintingThresholdUBA: BigNumberish,
      _largeMintingDelaySeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setDirectMintingOthersCanExecuteAfterSeconds: TypedContractMethod<
    [_seconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMintingTagManager: TypedContractMethod<
    [mintingTagManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setSmartAccountManager: TypedContractMethod<
    [_smartAccountManager: AddressLike],
    [void],
    "nonpayable"
  >;

  switchToProductionMode: TypedContractMethod<[], [void], "nonpayable">;

  unblockDirectMintingsUntil: TypedContractMethod<
    [_timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelGovernanceCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeGovernanceCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDirectMintingDailyLimitUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingDailyLimiterState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDirectMintingExecutorFeeUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingFeeBIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingFeeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingHourlyLimitUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingHourlyLimiterState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        _windowStartTimestamp: bigint;
        _mintedInCurrentWindow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDirectMintingLargeMintingDelaySeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingLargeMintingThresholdUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingMinimumFeeUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingOthersCanExecuteAfterSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDirectMintingsUnblockUntilTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMintingTagManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSmartAccountManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "governanceSettings"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isExecutor"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "productionMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setDirectMintingDailyLimitUBA"
  ): TypedContractMethod<[_dailyLimitUBA: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDirectMintingExecutorFee"
  ): TypedContractMethod<[_executorFeeUBA: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDirectMintingFee"
  ): TypedContractMethod<
    [_mintingFeeBIPS: BigNumberish, _minimumMintingFeeUBA: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDirectMintingFeeReceiver"
  ): TypedContractMethod<
    [_mintingFeeReceiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDirectMintingHourlyLimitUBA"
  ): TypedContractMethod<[_hourlyLimitUBA: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDirectMintingLargeMintingThrottling"
  ): TypedContractMethod<
    [
      _largeMintingThresholdUBA: BigNumberish,
      _largeMintingDelaySeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDirectMintingOthersCanExecuteAfterSeconds"
  ): TypedContractMethod<[_seconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMintingTagManager"
  ): TypedContractMethod<
    [mintingTagManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSmartAccountManager"
  ): TypedContractMethod<
    [_smartAccountManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "switchToProductionMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unblockDirectMintingsUntil"
  ): TypedContractMethod<[_timestamp: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ContractChanged"
  ): TypedContractEvent<
    ContractChangedEvent.InputTuple,
    ContractChangedEvent.OutputTuple,
    ContractChangedEvent.OutputObject
  >;
  getEvent(
    key: "DirectMintingsUnblocked"
  ): TypedContractEvent<
    DirectMintingsUnblockedEvent.InputTuple,
    DirectMintingsUnblockedEvent.OutputTuple,
    DirectMintingsUnblockedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceCallTimelocked"
  ): TypedContractEvent<
    GovernanceCallTimelockedEvent.InputTuple,
    GovernanceCallTimelockedEvent.OutputTuple,
    GovernanceCallTimelockedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceInitialised"
  ): TypedContractEvent<
    GovernanceInitialisedEvent.InputTuple,
    GovernanceInitialisedEvent.OutputTuple,
    GovernanceInitialisedEvent.OutputObject
  >;
  getEvent(
    key: "GovernedProductionModeEntered"
  ): TypedContractEvent<
    GovernedProductionModeEnteredEvent.InputTuple,
    GovernedProductionModeEnteredEvent.OutputTuple,
    GovernedProductionModeEnteredEvent.OutputObject
  >;
  getEvent(
    key: "SettingChanged"
  ): TypedContractEvent<
    SettingChangedEvent.InputTuple,
    SettingChangedEvent.OutputTuple,
    SettingChangedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedGovernanceCallCanceled"
  ): TypedContractEvent<
    TimelockedGovernanceCallCanceledEvent.InputTuple,
    TimelockedGovernanceCallCanceledEvent.OutputTuple,
    TimelockedGovernanceCallCanceledEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedGovernanceCallExecuted"
  ): TypedContractEvent<
    TimelockedGovernanceCallExecutedEvent.InputTuple,
    TimelockedGovernanceCallExecutedEvent.OutputTuple,
    TimelockedGovernanceCallExecutedEvent.OutputObject
  >;

  filters: {
    "ContractChanged(string,address)": TypedContractEvent<
      ContractChangedEvent.InputTuple,
      ContractChangedEvent.OutputTuple,
      ContractChangedEvent.OutputObject
    >;
    ContractChanged: TypedContractEvent<
      ContractChangedEvent.InputTuple,
      ContractChangedEvent.OutputTuple,
      ContractChangedEvent.OutputObject
    >;

    "DirectMintingsUnblocked(uint256)": TypedContractEvent<
      DirectMintingsUnblockedEvent.InputTuple,
      DirectMintingsUnblockedEvent.OutputTuple,
      DirectMintingsUnblockedEvent.OutputObject
    >;
    DirectMintingsUnblocked: TypedContractEvent<
      DirectMintingsUnblockedEvent.InputTuple,
      DirectMintingsUnblockedEvent.OutputTuple,
      DirectMintingsUnblockedEvent.OutputObject
    >;

    "GovernanceCallTimelocked(bytes,bytes32,uint256)": TypedContractEvent<
      GovernanceCallTimelockedEvent.InputTuple,
      GovernanceCallTimelockedEvent.OutputTuple,
      GovernanceCallTimelockedEvent.OutputObject
    >;
    GovernanceCallTimelocked: TypedContractEvent<
      GovernanceCallTimelockedEvent.InputTuple,
      GovernanceCallTimelockedEvent.OutputTuple,
      GovernanceCallTimelockedEvent.OutputObject
    >;

    "GovernanceInitialised(address)": TypedContractEvent<
      GovernanceInitialisedEvent.InputTuple,
      GovernanceInitialisedEvent.OutputTuple,
      GovernanceInitialisedEvent.OutputObject
    >;
    GovernanceInitialised: TypedContractEvent<
      GovernanceInitialisedEvent.InputTuple,
      GovernanceInitialisedEvent.OutputTuple,
      GovernanceInitialisedEvent.OutputObject
    >;

    "GovernedProductionModeEntered(address)": TypedContractEvent<
      GovernedProductionModeEnteredEvent.InputTuple,
      GovernedProductionModeEnteredEvent.OutputTuple,
      GovernedProductionModeEnteredEvent.OutputObject
    >;
    GovernedProductionModeEntered: TypedContractEvent<
      GovernedProductionModeEnteredEvent.InputTuple,
      GovernedProductionModeEnteredEvent.OutputTuple,
      GovernedProductionModeEnteredEvent.OutputObject
    >;

    "SettingChanged(string,uint256)": TypedContractEvent<
      SettingChangedEvent.InputTuple,
      SettingChangedEvent.OutputTuple,
      SettingChangedEvent.OutputObject
    >;
    SettingChanged: TypedContractEvent<
      SettingChangedEvent.InputTuple,
      SettingChangedEvent.OutputTuple,
      SettingChangedEvent.OutputObject
    >;

    "TimelockedGovernanceCallCanceled(bytes32)": TypedContractEvent<
      TimelockedGovernanceCallCanceledEvent.InputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputObject
    >;
    TimelockedGovernanceCallCanceled: TypedContractEvent<
      TimelockedGovernanceCallCanceledEvent.InputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputObject
    >;

    "TimelockedGovernanceCallExecuted(bytes32)": TypedContractEvent<
      TimelockedGovernanceCallExecutedEvent.InputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputObject
    >;
    TimelockedGovernanceCallExecuted: TypedContractEvent<
      TimelockedGovernanceCallExecutedEvent.InputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputObject
    >;
  };
}
