/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface LiquidationFacetInterface extends Interface {
  getFunction(
    nameOrSignature: "endLiquidation" | "liquidate" | "startLiquidation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DustChanged"
      | "LiquidationEnded"
      | "LiquidationPerformed"
      | "LiquidationStarted"
      | "RedemptionTicketDeleted"
      | "RedemptionTicketUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "endLiquidation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startLiquidation",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "endLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startLiquidation",
    data: BytesLike
  ): Result;
}

export namespace DustChangedEvent {
  export type InputTuple = [agentVault: AddressLike, dustUBA: BigNumberish];
  export type OutputTuple = [agentVault: string, dustUBA: bigint];
  export interface OutputObject {
    agentVault: string;
    dustUBA: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationEndedEvent {
  export type InputTuple = [agentVault: AddressLike];
  export type OutputTuple = [agentVault: string];
  export interface OutputObject {
    agentVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationPerformedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    liquidator: AddressLike,
    valueUBA: BigNumberish,
    paidVaultCollateralWei: BigNumberish,
    paidPoolCollateralWei: BigNumberish
  ];
  export type OutputTuple = [
    agentVault: string,
    liquidator: string,
    valueUBA: bigint,
    paidVaultCollateralWei: bigint,
    paidPoolCollateralWei: bigint
  ];
  export interface OutputObject {
    agentVault: string;
    liquidator: string;
    valueUBA: bigint;
    paidVaultCollateralWei: bigint;
    paidPoolCollateralWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationStartedEvent {
  export type InputTuple = [agentVault: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agentVault: string, timestamp: bigint];
  export interface OutputObject {
    agentVault: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionTicketDeletedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    redemptionTicketId: BigNumberish
  ];
  export type OutputTuple = [agentVault: string, redemptionTicketId: bigint];
  export interface OutputObject {
    agentVault: string;
    redemptionTicketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionTicketUpdatedEvent {
  export type InputTuple = [
    agentVault: AddressLike,
    redemptionTicketId: BigNumberish,
    ticketValueUBA: BigNumberish
  ];
  export type OutputTuple = [
    agentVault: string,
    redemptionTicketId: bigint,
    ticketValueUBA: bigint
  ];
  export interface OutputObject {
    agentVault: string;
    redemptionTicketId: bigint;
    ticketValueUBA: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidationFacet extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidationFacet;
  waitForDeployment(): Promise<this>;

  interface: LiquidationFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  endLiquidation: TypedContractMethod<
    [_agentVault: AddressLike],
    [void],
    "nonpayable"
  >;

  liquidate: TypedContractMethod<
    [_agentVault: AddressLike, _amountUBA: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        _liquidatedAmountUBA: bigint;
        _amountPaidVault: bigint;
        _amountPaidPool: bigint;
      }
    ],
    "nonpayable"
  >;

  startLiquidation: TypedContractMethod<
    [_agentVault: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "endLiquidation"
  ): TypedContractMethod<[_agentVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [_agentVault: AddressLike, _amountUBA: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        _liquidatedAmountUBA: bigint;
        _amountPaidVault: bigint;
        _amountPaidPool: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startLiquidation"
  ): TypedContractMethod<[_agentVault: AddressLike], [bigint], "nonpayable">;

  getEvent(
    key: "DustChanged"
  ): TypedContractEvent<
    DustChangedEvent.InputTuple,
    DustChangedEvent.OutputTuple,
    DustChangedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationEnded"
  ): TypedContractEvent<
    LiquidationEndedEvent.InputTuple,
    LiquidationEndedEvent.OutputTuple,
    LiquidationEndedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationPerformed"
  ): TypedContractEvent<
    LiquidationPerformedEvent.InputTuple,
    LiquidationPerformedEvent.OutputTuple,
    LiquidationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationStarted"
  ): TypedContractEvent<
    LiquidationStartedEvent.InputTuple,
    LiquidationStartedEvent.OutputTuple,
    LiquidationStartedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionTicketDeleted"
  ): TypedContractEvent<
    RedemptionTicketDeletedEvent.InputTuple,
    RedemptionTicketDeletedEvent.OutputTuple,
    RedemptionTicketDeletedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionTicketUpdated"
  ): TypedContractEvent<
    RedemptionTicketUpdatedEvent.InputTuple,
    RedemptionTicketUpdatedEvent.OutputTuple,
    RedemptionTicketUpdatedEvent.OutputObject
  >;

  filters: {
    "DustChanged(address,uint256)": TypedContractEvent<
      DustChangedEvent.InputTuple,
      DustChangedEvent.OutputTuple,
      DustChangedEvent.OutputObject
    >;
    DustChanged: TypedContractEvent<
      DustChangedEvent.InputTuple,
      DustChangedEvent.OutputTuple,
      DustChangedEvent.OutputObject
    >;

    "LiquidationEnded(address)": TypedContractEvent<
      LiquidationEndedEvent.InputTuple,
      LiquidationEndedEvent.OutputTuple,
      LiquidationEndedEvent.OutputObject
    >;
    LiquidationEnded: TypedContractEvent<
      LiquidationEndedEvent.InputTuple,
      LiquidationEndedEvent.OutputTuple,
      LiquidationEndedEvent.OutputObject
    >;

    "LiquidationPerformed(address,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidationPerformedEvent.InputTuple,
      LiquidationPerformedEvent.OutputTuple,
      LiquidationPerformedEvent.OutputObject
    >;
    LiquidationPerformed: TypedContractEvent<
      LiquidationPerformedEvent.InputTuple,
      LiquidationPerformedEvent.OutputTuple,
      LiquidationPerformedEvent.OutputObject
    >;

    "LiquidationStarted(address,uint256)": TypedContractEvent<
      LiquidationStartedEvent.InputTuple,
      LiquidationStartedEvent.OutputTuple,
      LiquidationStartedEvent.OutputObject
    >;
    LiquidationStarted: TypedContractEvent<
      LiquidationStartedEvent.InputTuple,
      LiquidationStartedEvent.OutputTuple,
      LiquidationStartedEvent.OutputObject
    >;

    "RedemptionTicketDeleted(address,uint256)": TypedContractEvent<
      RedemptionTicketDeletedEvent.InputTuple,
      RedemptionTicketDeletedEvent.OutputTuple,
      RedemptionTicketDeletedEvent.OutputObject
    >;
    RedemptionTicketDeleted: TypedContractEvent<
      RedemptionTicketDeletedEvent.InputTuple,
      RedemptionTicketDeletedEvent.OutputTuple,
      RedemptionTicketDeletedEvent.OutputObject
    >;

    "RedemptionTicketUpdated(address,uint256,uint256)": TypedContractEvent<
      RedemptionTicketUpdatedEvent.InputTuple,
      RedemptionTicketUpdatedEvent.OutputTuple,
      RedemptionTicketUpdatedEvent.OutputObject
    >;
    RedemptionTicketUpdated: TypedContractEvent<
      RedemptionTicketUpdatedEvent.InputTuple,
      RedemptionTicketUpdatedEvent.OutputTuple,
      RedemptionTicketUpdatedEvent.OutputObject
    >;
  };
}
