/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace AssetManagerSettings {
  export type DataStruct = {
    assetManagerController: AddressLike;
    fAsset: AddressLike;
    agentVaultFactory: AddressLike;
    collateralPoolFactory: AddressLike;
    collateralPoolTokenFactory: AddressLike;
    poolTokenSuffix: string;
    __whitelist: AddressLike;
    agentOwnerRegistry: AddressLike;
    fdcVerification: AddressLike;
    burnAddress: AddressLike;
    priceReader: AddressLike;
    assetDecimals: BigNumberish;
    assetMintingDecimals: BigNumberish;
    chainId: BytesLike;
    averageBlockTimeMS: BigNumberish;
    mintingPoolHoldingsRequiredBIPS: BigNumberish;
    collateralReservationFeeBIPS: BigNumberish;
    assetUnitUBA: BigNumberish;
    assetMintingGranularityUBA: BigNumberish;
    lotSizeAMG: BigNumberish;
    __minUnderlyingBackingBIPS: BigNumberish;
    __requireEOAAddressProof: boolean;
    mintingCapAMG: BigNumberish;
    underlyingBlocksForPayment: BigNumberish;
    underlyingSecondsForPayment: BigNumberish;
    redemptionFeeBIPS: BigNumberish;
    redemptionDefaultFactorVaultCollateralBIPS: BigNumberish;
    __redemptionDefaultFactorPoolBIPS: BigNumberish;
    confirmationByOthersAfterSeconds: BigNumberish;
    confirmationByOthersRewardUSD5: BigNumberish;
    maxRedeemedTickets: BigNumberish;
    paymentChallengeRewardBIPS: BigNumberish;
    paymentChallengeRewardUSD5: BigNumberish;
    withdrawalWaitMinSeconds: BigNumberish;
    maxTrustedPriceAgeSeconds: BigNumberish;
    __ccbTimeSeconds: BigNumberish;
    attestationWindowSeconds: BigNumberish;
    minUpdateRepeatTimeSeconds: BigNumberish;
    __buybackCollateralFactorBIPS: BigNumberish;
    __announcedUnderlyingConfirmationMinSeconds: BigNumberish;
    __tokenInvalidationTimeMinSeconds: BigNumberish;
    vaultCollateralBuyForFlareFactorBIPS: BigNumberish;
    agentExitAvailableTimelockSeconds: BigNumberish;
    agentFeeChangeTimelockSeconds: BigNumberish;
    agentMintingCRChangeTimelockSeconds: BigNumberish;
    poolExitCRChangeTimelockSeconds: BigNumberish;
    agentTimelockedOperationWindowSeconds: BigNumberish;
    collateralPoolTokenTimelockSeconds: BigNumberish;
    liquidationStepSeconds: BigNumberish;
    liquidationCollateralFactorBIPS: BigNumberish[];
    liquidationFactorVaultCollateralBIPS: BigNumberish[];
    diamondCutMinTimelockSeconds: BigNumberish;
    maxEmergencyPauseDurationSeconds: BigNumberish;
    emergencyPauseDurationResetAfterSeconds: BigNumberish;
    __cancelCollateralReservationAfterSeconds: BigNumberish;
    __rejectOrCancelCollateralReservationReturnFactorBIPS: BigNumberish;
    __rejectRedemptionRequestWindowSeconds: BigNumberish;
    __takeOverRedemptionRequestWindowSeconds: BigNumberish;
    __rejectedRedemptionDefaultFactorVaultCollateralBIPS: BigNumberish;
    __rejectedRedemptionDefaultFactorPoolBIPS: BigNumberish;
  };

  export type DataStructOutput = [
    assetManagerController: string,
    fAsset: string,
    agentVaultFactory: string,
    collateralPoolFactory: string,
    collateralPoolTokenFactory: string,
    poolTokenSuffix: string,
    __whitelist: string,
    agentOwnerRegistry: string,
    fdcVerification: string,
    burnAddress: string,
    priceReader: string,
    assetDecimals: bigint,
    assetMintingDecimals: bigint,
    chainId: string,
    averageBlockTimeMS: bigint,
    mintingPoolHoldingsRequiredBIPS: bigint,
    collateralReservationFeeBIPS: bigint,
    assetUnitUBA: bigint,
    assetMintingGranularityUBA: bigint,
    lotSizeAMG: bigint,
    __minUnderlyingBackingBIPS: bigint,
    __requireEOAAddressProof: boolean,
    mintingCapAMG: bigint,
    underlyingBlocksForPayment: bigint,
    underlyingSecondsForPayment: bigint,
    redemptionFeeBIPS: bigint,
    redemptionDefaultFactorVaultCollateralBIPS: bigint,
    __redemptionDefaultFactorPoolBIPS: bigint,
    confirmationByOthersAfterSeconds: bigint,
    confirmationByOthersRewardUSD5: bigint,
    maxRedeemedTickets: bigint,
    paymentChallengeRewardBIPS: bigint,
    paymentChallengeRewardUSD5: bigint,
    withdrawalWaitMinSeconds: bigint,
    maxTrustedPriceAgeSeconds: bigint,
    __ccbTimeSeconds: bigint,
    attestationWindowSeconds: bigint,
    minUpdateRepeatTimeSeconds: bigint,
    __buybackCollateralFactorBIPS: bigint,
    __announcedUnderlyingConfirmationMinSeconds: bigint,
    __tokenInvalidationTimeMinSeconds: bigint,
    vaultCollateralBuyForFlareFactorBIPS: bigint,
    agentExitAvailableTimelockSeconds: bigint,
    agentFeeChangeTimelockSeconds: bigint,
    agentMintingCRChangeTimelockSeconds: bigint,
    poolExitCRChangeTimelockSeconds: bigint,
    agentTimelockedOperationWindowSeconds: bigint,
    collateralPoolTokenTimelockSeconds: bigint,
    liquidationStepSeconds: bigint,
    liquidationCollateralFactorBIPS: bigint[],
    liquidationFactorVaultCollateralBIPS: bigint[],
    diamondCutMinTimelockSeconds: bigint,
    maxEmergencyPauseDurationSeconds: bigint,
    emergencyPauseDurationResetAfterSeconds: bigint,
    __cancelCollateralReservationAfterSeconds: bigint,
    __rejectOrCancelCollateralReservationReturnFactorBIPS: bigint,
    __rejectRedemptionRequestWindowSeconds: bigint,
    __takeOverRedemptionRequestWindowSeconds: bigint,
    __rejectedRedemptionDefaultFactorVaultCollateralBIPS: bigint,
    __rejectedRedemptionDefaultFactorPoolBIPS: bigint
  ] & {
    assetManagerController: string;
    fAsset: string;
    agentVaultFactory: string;
    collateralPoolFactory: string;
    collateralPoolTokenFactory: string;
    poolTokenSuffix: string;
    __whitelist: string;
    agentOwnerRegistry: string;
    fdcVerification: string;
    burnAddress: string;
    priceReader: string;
    assetDecimals: bigint;
    assetMintingDecimals: bigint;
    chainId: string;
    averageBlockTimeMS: bigint;
    mintingPoolHoldingsRequiredBIPS: bigint;
    collateralReservationFeeBIPS: bigint;
    assetUnitUBA: bigint;
    assetMintingGranularityUBA: bigint;
    lotSizeAMG: bigint;
    __minUnderlyingBackingBIPS: bigint;
    __requireEOAAddressProof: boolean;
    mintingCapAMG: bigint;
    underlyingBlocksForPayment: bigint;
    underlyingSecondsForPayment: bigint;
    redemptionFeeBIPS: bigint;
    redemptionDefaultFactorVaultCollateralBIPS: bigint;
    __redemptionDefaultFactorPoolBIPS: bigint;
    confirmationByOthersAfterSeconds: bigint;
    confirmationByOthersRewardUSD5: bigint;
    maxRedeemedTickets: bigint;
    paymentChallengeRewardBIPS: bigint;
    paymentChallengeRewardUSD5: bigint;
    withdrawalWaitMinSeconds: bigint;
    maxTrustedPriceAgeSeconds: bigint;
    __ccbTimeSeconds: bigint;
    attestationWindowSeconds: bigint;
    minUpdateRepeatTimeSeconds: bigint;
    __buybackCollateralFactorBIPS: bigint;
    __announcedUnderlyingConfirmationMinSeconds: bigint;
    __tokenInvalidationTimeMinSeconds: bigint;
    vaultCollateralBuyForFlareFactorBIPS: bigint;
    agentExitAvailableTimelockSeconds: bigint;
    agentFeeChangeTimelockSeconds: bigint;
    agentMintingCRChangeTimelockSeconds: bigint;
    poolExitCRChangeTimelockSeconds: bigint;
    agentTimelockedOperationWindowSeconds: bigint;
    collateralPoolTokenTimelockSeconds: bigint;
    liquidationStepSeconds: bigint;
    liquidationCollateralFactorBIPS: bigint[];
    liquidationFactorVaultCollateralBIPS: bigint[];
    diamondCutMinTimelockSeconds: bigint;
    maxEmergencyPauseDurationSeconds: bigint;
    emergencyPauseDurationResetAfterSeconds: bigint;
    __cancelCollateralReservationAfterSeconds: bigint;
    __rejectOrCancelCollateralReservationReturnFactorBIPS: bigint;
    __rejectRedemptionRequestWindowSeconds: bigint;
    __takeOverRedemptionRequestWindowSeconds: bigint;
    __rejectedRedemptionDefaultFactorVaultCollateralBIPS: bigint;
    __rejectedRedemptionDefaultFactorPoolBIPS: bigint;
  };
}

export interface SettingsReaderFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetManagerController"
      | "assetMintingDecimals"
      | "assetMintingGranularityUBA"
      | "fAsset"
      | "getCollateralPoolTokenTimelockSeconds"
      | "getSettings"
      | "lotSize"
      | "priceReader"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assetManagerController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetMintingDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetMintingGranularityUBA",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fAsset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCollateralPoolTokenTimelockSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettings",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lotSize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceReader",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "assetManagerController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetMintingDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetMintingGranularityUBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollateralPoolTokenTimelockSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lotSize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceReader",
    data: BytesLike
  ): Result;
}

export interface SettingsReaderFacet extends BaseContract {
  connect(runner?: ContractRunner | null): SettingsReaderFacet;
  waitForDeployment(): Promise<this>;

  interface: SettingsReaderFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetManagerController: TypedContractMethod<[], [string], "view">;

  assetMintingDecimals: TypedContractMethod<[], [bigint], "view">;

  assetMintingGranularityUBA: TypedContractMethod<[], [bigint], "view">;

  fAsset: TypedContractMethod<[], [string], "view">;

  getCollateralPoolTokenTimelockSeconds: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  getSettings: TypedContractMethod<
    [],
    [AssetManagerSettings.DataStructOutput],
    "view"
  >;

  lotSize: TypedContractMethod<[], [bigint], "view">;

  priceReader: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetManagerController"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetMintingDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assetMintingGranularityUBA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCollateralPoolTokenTimelockSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSettings"
  ): TypedContractMethod<[], [AssetManagerSettings.DataStructOutput], "view">;
  getFunction(
    nameOrSignature: "lotSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceReader"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
