/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace RedemptionTicketInfo {
  export type DataStruct = {
    redemptionTicketId: BigNumberish;
    agentVault: AddressLike;
    ticketValueUBA: BigNumberish;
  };

  export type DataStructOutput = [
    redemptionTicketId: bigint,
    agentVault: string,
    ticketValueUBA: bigint
  ] & {
    redemptionTicketId: bigint;
    agentVault: string;
    ticketValueUBA: bigint;
  };
}

export declare namespace CollateralReservationInfo {
  export type DataStruct = {
    collateralReservationId: BigNumberish;
    agentVault: AddressLike;
    minter: AddressLike;
    paymentAddress: string;
    paymentReference: BytesLike;
    valueUBA: BigNumberish;
    mintingFeeUBA: BigNumberish;
    reservationFeeNatWei: BigNumberish;
    poolFeeShareBIPS: BigNumberish;
    firstUnderlyingBlock: BigNumberish;
    lastUnderlyingBlock: BigNumberish;
    lastUnderlyingTimestamp: BigNumberish;
    executor: AddressLike;
    executorFeeNatWei: BigNumberish;
    status: BigNumberish;
  };

  export type DataStructOutput = [
    collateralReservationId: bigint,
    agentVault: string,
    minter: string,
    paymentAddress: string,
    paymentReference: string,
    valueUBA: bigint,
    mintingFeeUBA: bigint,
    reservationFeeNatWei: bigint,
    poolFeeShareBIPS: bigint,
    firstUnderlyingBlock: bigint,
    lastUnderlyingBlock: bigint,
    lastUnderlyingTimestamp: bigint,
    executor: string,
    executorFeeNatWei: bigint,
    status: bigint
  ] & {
    collateralReservationId: bigint;
    agentVault: string;
    minter: string;
    paymentAddress: string;
    paymentReference: string;
    valueUBA: bigint;
    mintingFeeUBA: bigint;
    reservationFeeNatWei: bigint;
    poolFeeShareBIPS: bigint;
    firstUnderlyingBlock: bigint;
    lastUnderlyingBlock: bigint;
    lastUnderlyingTimestamp: bigint;
    executor: string;
    executorFeeNatWei: bigint;
    status: bigint;
  };
}

export declare namespace RedemptionRequestInfo {
  export type DataStruct = {
    redemptionRequestId: BigNumberish;
    status: BigNumberish;
    agentVault: AddressLike;
    redeemer: AddressLike;
    paymentAddress: string;
    paymentReference: BytesLike;
    valueUBA: BigNumberish;
    feeUBA: BigNumberish;
    poolFeeShareBIPS: BigNumberish;
    firstUnderlyingBlock: BigNumberish;
    lastUnderlyingBlock: BigNumberish;
    lastUnderlyingTimestamp: BigNumberish;
    timestamp: BigNumberish;
    poolSelfClose: boolean;
    transferToCoreVault: boolean;
    executor: AddressLike;
    executorFeeNatWei: BigNumberish;
  };

  export type DataStructOutput = [
    redemptionRequestId: bigint,
    status: bigint,
    agentVault: string,
    redeemer: string,
    paymentAddress: string,
    paymentReference: string,
    valueUBA: bigint,
    feeUBA: bigint,
    poolFeeShareBIPS: bigint,
    firstUnderlyingBlock: bigint,
    lastUnderlyingBlock: bigint,
    lastUnderlyingTimestamp: bigint,
    timestamp: bigint,
    poolSelfClose: boolean,
    transferToCoreVault: boolean,
    executor: string,
    executorFeeNatWei: bigint
  ] & {
    redemptionRequestId: bigint;
    status: bigint;
    agentVault: string;
    redeemer: string;
    paymentAddress: string;
    paymentReference: string;
    valueUBA: bigint;
    feeUBA: bigint;
    poolFeeShareBIPS: bigint;
    firstUnderlyingBlock: bigint;
    lastUnderlyingBlock: bigint;
    lastUnderlyingTimestamp: bigint;
    timestamp: bigint;
    poolSelfClose: boolean;
    transferToCoreVault: boolean;
    executor: string;
    executorFeeNatWei: bigint;
  };

  export type DataExtStruct = {
    redemptionRequestId: BigNumberish;
    status: BigNumberish;
    agentVault: AddressLike;
    redeemer: AddressLike;
    paymentAddress: string;
    paymentReference: BytesLike;
    valueUBA: BigNumberish;
    feeUBA: BigNumberish;
    poolFeeShareBIPS: BigNumberish;
    firstUnderlyingBlock: BigNumberish;
    lastUnderlyingBlock: BigNumberish;
    lastUnderlyingTimestamp: BigNumberish;
    timestamp: BigNumberish;
    poolSelfClose: boolean;
    transferToCoreVault: boolean;
    executor: AddressLike;
    executorFeeNatWei: BigNumberish;
    requiresDestinationTag: boolean;
    destinationTag: BigNumberish;
  };

  export type DataExtStructOutput = [
    redemptionRequestId: bigint,
    status: bigint,
    agentVault: string,
    redeemer: string,
    paymentAddress: string,
    paymentReference: string,
    valueUBA: bigint,
    feeUBA: bigint,
    poolFeeShareBIPS: bigint,
    firstUnderlyingBlock: bigint,
    lastUnderlyingBlock: bigint,
    lastUnderlyingTimestamp: bigint,
    timestamp: bigint,
    poolSelfClose: boolean,
    transferToCoreVault: boolean,
    executor: string,
    executorFeeNatWei: bigint,
    requiresDestinationTag: boolean,
    destinationTag: bigint
  ] & {
    redemptionRequestId: bigint;
    status: bigint;
    agentVault: string;
    redeemer: string;
    paymentAddress: string;
    paymentReference: string;
    valueUBA: bigint;
    feeUBA: bigint;
    poolFeeShareBIPS: bigint;
    firstUnderlyingBlock: bigint;
    lastUnderlyingBlock: bigint;
    lastUnderlyingTimestamp: bigint;
    timestamp: bigint;
    poolSelfClose: boolean;
    transferToCoreVault: boolean;
    executor: string;
    executorFeeNatWei: bigint;
    requiresDestinationTag: boolean;
    destinationTag: bigint;
  };
}

export interface SystemInfoFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRedemptionQueue"
      | "collateralReservationInfo"
      | "controllerAttached"
      | "mintingPaused"
      | "redemptionQueue"
      | "redemptionRequestInfo"
      | "redemptionRequestInfoExt"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "agentRedemptionQueue",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralReservationInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "controllerAttached",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintingPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionQueue",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionRequestInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionRequestInfoExt",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRedemptionQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralReservationInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllerAttached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionRequestInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionRequestInfoExt",
    data: BytesLike
  ): Result;
}

export interface SystemInfoFacet extends BaseContract {
  connect(runner?: ContractRunner | null): SystemInfoFacet;
  waitForDeployment(): Promise<this>;

  interface: SystemInfoFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRedemptionQueue: TypedContractMethod<
    [
      _agentVault: AddressLike,
      _firstRedemptionTicketId: BigNumberish,
      _pageSize: BigNumberish
    ],
    [
      [RedemptionTicketInfo.DataStructOutput[], bigint] & {
        _queue: RedemptionTicketInfo.DataStructOutput[];
        _nextRedemptionTicketId: bigint;
      }
    ],
    "view"
  >;

  collateralReservationInfo: TypedContractMethod<
    [_collateralReservationId: BigNumberish],
    [CollateralReservationInfo.DataStructOutput],
    "view"
  >;

  controllerAttached: TypedContractMethod<[], [boolean], "view">;

  mintingPaused: TypedContractMethod<[], [boolean], "view">;

  redemptionQueue: TypedContractMethod<
    [_firstRedemptionTicketId: BigNumberish, _pageSize: BigNumberish],
    [
      [RedemptionTicketInfo.DataStructOutput[], bigint] & {
        _queue: RedemptionTicketInfo.DataStructOutput[];
        _nextRedemptionTicketId: bigint;
      }
    ],
    "view"
  >;

  redemptionRequestInfo: TypedContractMethod<
    [_redemptionRequestId: BigNumberish],
    [RedemptionRequestInfo.DataStructOutput],
    "view"
  >;

  redemptionRequestInfoExt: TypedContractMethod<
    [_redemptionRequestId: BigNumberish],
    [RedemptionRequestInfo.DataExtStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRedemptionQueue"
  ): TypedContractMethod<
    [
      _agentVault: AddressLike,
      _firstRedemptionTicketId: BigNumberish,
      _pageSize: BigNumberish
    ],
    [
      [RedemptionTicketInfo.DataStructOutput[], bigint] & {
        _queue: RedemptionTicketInfo.DataStructOutput[];
        _nextRedemptionTicketId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "collateralReservationInfo"
  ): TypedContractMethod<
    [_collateralReservationId: BigNumberish],
    [CollateralReservationInfo.DataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "controllerAttached"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintingPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "redemptionQueue"
  ): TypedContractMethod<
    [_firstRedemptionTicketId: BigNumberish, _pageSize: BigNumberish],
    [
      [RedemptionTicketInfo.DataStructOutput[], bigint] & {
        _queue: RedemptionTicketInfo.DataStructOutput[];
        _nextRedemptionTicketId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "redemptionRequestInfo"
  ): TypedContractMethod<
    [_redemptionRequestId: BigNumberish],
    [RedemptionRequestInfo.DataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "redemptionRequestInfoExt"
  ): TypedContractMethod<
    [_redemptionRequestId: BigNumberish],
    [RedemptionRequestInfo.DataExtStructOutput],
    "view"
  >;

  filters: {};
}
