/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IConfirmedBlockHeightExists {
  export type RequestBodyStruct = {
    blockNumber: BigNumberish;
    queryWindow: BigNumberish;
  };

  export type RequestBodyStructOutput = [
    blockNumber: bigint,
    queryWindow: bigint
  ] & { blockNumber: bigint; queryWindow: bigint };

  export type ResponseBodyStruct = {
    blockTimestamp: BigNumberish;
    numberOfConfirmations: BigNumberish;
    lowestQueryWindowBlockNumber: BigNumberish;
    lowestQueryWindowBlockTimestamp: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    blockTimestamp: bigint,
    numberOfConfirmations: bigint,
    lowestQueryWindowBlockNumber: bigint,
    lowestQueryWindowBlockTimestamp: bigint
  ] & {
    blockTimestamp: bigint;
    numberOfConfirmations: bigint;
    lowestQueryWindowBlockNumber: bigint;
    lowestQueryWindowBlockTimestamp: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IConfirmedBlockHeightExists.RequestBodyStruct;
    responseBody: IConfirmedBlockHeightExists.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IConfirmedBlockHeightExists.RequestBodyStructOutput,
    responseBody: IConfirmedBlockHeightExists.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IConfirmedBlockHeightExists.RequestBodyStructOutput;
    responseBody: IConfirmedBlockHeightExists.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IConfirmedBlockHeightExists.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IConfirmedBlockHeightExists.ResponseStructOutput
  ] & {
    merkleProof: string[];
    data: IConfirmedBlockHeightExists.ResponseStructOutput;
  };
}

export interface UnderlyingTimekeepingFacetInterface extends Interface {
  getFunction(
    nameOrSignature: "currentUnderlyingBlock" | "updateCurrentBlock"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CurrentUnderlyingBlockUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "currentUnderlyingBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCurrentBlock",
    values: [IConfirmedBlockHeightExists.ProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentUnderlyingBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCurrentBlock",
    data: BytesLike
  ): Result;
}

export namespace CurrentUnderlyingBlockUpdatedEvent {
  export type InputTuple = [
    underlyingBlockNumber: BigNumberish,
    underlyingBlockTimestamp: BigNumberish,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    underlyingBlockNumber: bigint,
    underlyingBlockTimestamp: bigint,
    updatedAt: bigint
  ];
  export interface OutputObject {
    underlyingBlockNumber: bigint;
    underlyingBlockTimestamp: bigint;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UnderlyingTimekeepingFacet extends BaseContract {
  connect(runner?: ContractRunner | null): UnderlyingTimekeepingFacet;
  waitForDeployment(): Promise<this>;

  interface: UnderlyingTimekeepingFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentUnderlyingBlock: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _blockNumber: bigint;
        _blockTimestamp: bigint;
        _lastUpdateTs: bigint;
      }
    ],
    "view"
  >;

  updateCurrentBlock: TypedContractMethod<
    [_proof: IConfirmedBlockHeightExists.ProofStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentUnderlyingBlock"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _blockNumber: bigint;
        _blockTimestamp: bigint;
        _lastUpdateTs: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateCurrentBlock"
  ): TypedContractMethod<
    [_proof: IConfirmedBlockHeightExists.ProofStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CurrentUnderlyingBlockUpdated"
  ): TypedContractEvent<
    CurrentUnderlyingBlockUpdatedEvent.InputTuple,
    CurrentUnderlyingBlockUpdatedEvent.OutputTuple,
    CurrentUnderlyingBlockUpdatedEvent.OutputObject
  >;

  filters: {
    "CurrentUnderlyingBlockUpdated(uint256,uint256,uint256)": TypedContractEvent<
      CurrentUnderlyingBlockUpdatedEvent.InputTuple,
      CurrentUnderlyingBlockUpdatedEvent.OutputTuple,
      CurrentUnderlyingBlockUpdatedEvent.OutputObject
    >;
    CurrentUnderlyingBlockUpdated: TypedContractEvent<
      CurrentUnderlyingBlockUpdatedEvent.InputTuple,
      CurrentUnderlyingBlockUpdatedEvent.OutputTuple,
      CurrentUnderlyingBlockUpdatedEvent.OutputObject
    >;
  };
}
