/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface GovernanceSettingsMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SIGNAL_COINBASE"
      | "getExecutors"
      | "getGovernanceAddress"
      | "getTimelock"
      | "initialise"
      | "isExecutor"
      | "setExecutors"
      | "setGovernanceAddress"
      | "setTimelock"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GovernanceAddressUpdated"
      | "GovernanceExecutorsUpdated"
      | "GovernanceTimelockUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "SIGNAL_COINBASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGovernanceAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialise",
    values: [AddressLike, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutors",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernanceAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelock",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "SIGNAL_COINBASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGovernanceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialise", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExecutor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernanceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelock",
    data: BytesLike
  ): Result;
}

export namespace GovernanceAddressUpdatedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    oldGovernanceAddress: AddressLike,
    newGovernanceAddress: AddressLike
  ];
  export type OutputTuple = [
    timestamp: bigint,
    oldGovernanceAddress: string,
    newGovernanceAddress: string
  ];
  export interface OutputObject {
    timestamp: bigint;
    oldGovernanceAddress: string;
    newGovernanceAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceExecutorsUpdatedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    oldExecutors: AddressLike[],
    newExecutors: AddressLike[]
  ];
  export type OutputTuple = [
    timestamp: bigint,
    oldExecutors: string[],
    newExecutors: string[]
  ];
  export interface OutputObject {
    timestamp: bigint;
    oldExecutors: string[];
    newExecutors: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceTimelockUpdatedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    oldTimelock: BigNumberish,
    newTimelock: BigNumberish
  ];
  export type OutputTuple = [
    timestamp: bigint,
    oldTimelock: bigint,
    newTimelock: bigint
  ];
  export interface OutputObject {
    timestamp: bigint;
    oldTimelock: bigint;
    newTimelock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceSettingsMock extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceSettingsMock;
  waitForDeployment(): Promise<this>;

  interface: GovernanceSettingsMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SIGNAL_COINBASE: TypedContractMethod<[], [string], "view">;

  getExecutors: TypedContractMethod<[], [string[]], "view">;

  getGovernanceAddress: TypedContractMethod<[], [string], "view">;

  getTimelock: TypedContractMethod<[], [bigint], "view">;

  initialise: TypedContractMethod<
    [
      _governanceAddress: AddressLike,
      _timelock: BigNumberish,
      _executors: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  isExecutor: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  setExecutors: TypedContractMethod<
    [_newExecutors: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setGovernanceAddress: TypedContractMethod<
    [_newGovernance: AddressLike],
    [void],
    "nonpayable"
  >;

  setTimelock: TypedContractMethod<
    [_newTimelock: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SIGNAL_COINBASE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExecutors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGovernanceAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTimelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialise"
  ): TypedContractMethod<
    [
      _governanceAddress: AddressLike,
      _timelock: BigNumberish,
      _executors: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isExecutor"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setExecutors"
  ): TypedContractMethod<[_newExecutors: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGovernanceAddress"
  ): TypedContractMethod<[_newGovernance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimelock"
  ): TypedContractMethod<[_newTimelock: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "GovernanceAddressUpdated"
  ): TypedContractEvent<
    GovernanceAddressUpdatedEvent.InputTuple,
    GovernanceAddressUpdatedEvent.OutputTuple,
    GovernanceAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceExecutorsUpdated"
  ): TypedContractEvent<
    GovernanceExecutorsUpdatedEvent.InputTuple,
    GovernanceExecutorsUpdatedEvent.OutputTuple,
    GovernanceExecutorsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceTimelockUpdated"
  ): TypedContractEvent<
    GovernanceTimelockUpdatedEvent.InputTuple,
    GovernanceTimelockUpdatedEvent.OutputTuple,
    GovernanceTimelockUpdatedEvent.OutputObject
  >;

  filters: {
    "GovernanceAddressUpdated(uint256,address,address)": TypedContractEvent<
      GovernanceAddressUpdatedEvent.InputTuple,
      GovernanceAddressUpdatedEvent.OutputTuple,
      GovernanceAddressUpdatedEvent.OutputObject
    >;
    GovernanceAddressUpdated: TypedContractEvent<
      GovernanceAddressUpdatedEvent.InputTuple,
      GovernanceAddressUpdatedEvent.OutputTuple,
      GovernanceAddressUpdatedEvent.OutputObject
    >;

    "GovernanceExecutorsUpdated(uint256,address[],address[])": TypedContractEvent<
      GovernanceExecutorsUpdatedEvent.InputTuple,
      GovernanceExecutorsUpdatedEvent.OutputTuple,
      GovernanceExecutorsUpdatedEvent.OutputObject
    >;
    GovernanceExecutorsUpdated: TypedContractEvent<
      GovernanceExecutorsUpdatedEvent.InputTuple,
      GovernanceExecutorsUpdatedEvent.OutputTuple,
      GovernanceExecutorsUpdatedEvent.OutputObject
    >;

    "GovernanceTimelockUpdated(uint256,uint256,uint256)": TypedContractEvent<
      GovernanceTimelockUpdatedEvent.InputTuple,
      GovernanceTimelockUpdatedEvent.OutputTuple,
      GovernanceTimelockUpdatedEvent.OutputObject
    >;
    GovernanceTimelockUpdated: TypedContractEvent<
      GovernanceTimelockUpdatedEvent.InputTuple,
      GovernanceTimelockUpdatedEvent.OutputTuple,
      GovernanceTimelockUpdatedEvent.OutputObject
    >;
  };
}
