/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICheckPointable,
  ICheckPointableInterface,
} from "../../../../contracts/fassetToken/interfaces/ICheckPointable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_blockNumber",
        type: "uint256",
      },
    ],
    name: "balanceOfAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_blockNumber",
        type: "uint256",
      },
    ],
    name: "totalSupplyAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICheckPointable__factory {
  static readonly abi = _abi;
  static createInterface(): ICheckPointableInterface {
    return new Interface(_abi) as ICheckPointableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICheckPointable {
    return new Contract(address, _abi, runner) as unknown as ICheckPointable;
  }
}
