/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface DistributionToDelegatorsInterface extends Interface {
  getFunction(nameOrSignature: "claim" | "optOutOfAirdrop"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OptedOutOfAirdrop"): EventFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [AddressLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "optOutOfAirdrop",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "optOutOfAirdrop",
    data: BytesLike
  ): Result;
}

export namespace OptedOutOfAirdropEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DistributionToDelegators extends BaseContract {
  connect(runner?: ContractRunner | null): DistributionToDelegators;
  waitForDeployment(): Promise<this>;

  interface: DistributionToDelegatorsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<
    [
      arg0: AddressLike,
      _recipient: AddressLike,
      arg2: BigNumberish,
      arg3: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  optOutOfAirdrop: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      _recipient: AddressLike,
      arg2: BigNumberish,
      arg3: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "optOutOfAirdrop"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OptedOutOfAirdrop"
  ): TypedContractEvent<
    OptedOutOfAirdropEvent.InputTuple,
    OptedOutOfAirdropEvent.OutputTuple,
    OptedOutOfAirdropEvent.OutputObject
  >;

  filters: {
    "OptedOutOfAirdrop(address)": TypedContractEvent<
      OptedOutOfAirdropEvent.InputTuple,
      OptedOutOfAirdropEvent.OutputTuple,
      OptedOutOfAirdropEvent.OutputObject
    >;
    OptedOutOfAirdrop: TypedContractEvent<
      OptedOutOfAirdropEvent.InputTuple,
      OptedOutOfAirdropEvent.OutputTuple,
      OptedOutOfAirdropEvent.OutputObject
    >;
  };
}
