/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IReferencedPaymentNonexistence {
  export type RequestBodyStruct = {
    minimalBlockNumber: BigNumberish;
    deadlineBlockNumber: BigNumberish;
    deadlineTimestamp: BigNumberish;
    destinationAddressHash: BytesLike;
    amount: BigNumberish;
    standardPaymentReference: BytesLike;
    checkSourceAddresses: boolean;
    sourceAddressesRoot: BytesLike;
  };

  export type RequestBodyStructOutput = [
    minimalBlockNumber: bigint,
    deadlineBlockNumber: bigint,
    deadlineTimestamp: bigint,
    destinationAddressHash: string,
    amount: bigint,
    standardPaymentReference: string,
    checkSourceAddresses: boolean,
    sourceAddressesRoot: string
  ] & {
    minimalBlockNumber: bigint;
    deadlineBlockNumber: bigint;
    deadlineTimestamp: bigint;
    destinationAddressHash: string;
    amount: bigint;
    standardPaymentReference: string;
    checkSourceAddresses: boolean;
    sourceAddressesRoot: string;
  };

  export type ResponseBodyStruct = {
    minimalBlockTimestamp: BigNumberish;
    firstOverflowBlockNumber: BigNumberish;
    firstOverflowBlockTimestamp: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    minimalBlockTimestamp: bigint,
    firstOverflowBlockNumber: bigint,
    firstOverflowBlockTimestamp: bigint
  ] & {
    minimalBlockTimestamp: bigint;
    firstOverflowBlockNumber: bigint;
    firstOverflowBlockTimestamp: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IReferencedPaymentNonexistence.RequestBodyStruct;
    responseBody: IReferencedPaymentNonexistence.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IReferencedPaymentNonexistence.RequestBodyStructOutput,
    responseBody: IReferencedPaymentNonexistence.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IReferencedPaymentNonexistence.RequestBodyStructOutput;
    responseBody: IReferencedPaymentNonexistence.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IReferencedPaymentNonexistence.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IReferencedPaymentNonexistence.ResponseStructOutput
  ] & {
    merkleProof: string[];
    data: IReferencedPaymentNonexistence.ResponseStructOutput;
  };
}

export interface MaliciousExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "defaulting"
      | "diamond"
      | "hit"
      | "howMuchIsMyNativeBalance"
      | "tempProof"
      | "tempRequestId"
      | "trigger"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "defaulting",
    values: [
      IReferencedPaymentNonexistence.ProofStruct,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "diamond", values?: undefined): string;
  encodeFunctionData(functionFragment: "hit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "howMuchIsMyNativeBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tempProof", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tempRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "trigger", values?: undefined): string;

  decodeFunctionResult(functionFragment: "defaulting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "diamond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "howMuchIsMyNativeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tempProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tempRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trigger", data: BytesLike): Result;
}

export interface MaliciousExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): MaliciousExecutor;
  waitForDeployment(): Promise<this>;

  interface: MaliciousExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  defaulting: TypedContractMethod<
    [
      _proof: IReferencedPaymentNonexistence.ProofStruct,
      _redemptionRequestId: BigNumberish,
      _trigger: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  diamond: TypedContractMethod<[], [string], "view">;

  hit: TypedContractMethod<[], [bigint], "view">;

  howMuchIsMyNativeBalance: TypedContractMethod<[], [bigint], "view">;

  tempProof: TypedContractMethod<
    [],
    [IReferencedPaymentNonexistence.ResponseStructOutput],
    "view"
  >;

  tempRequestId: TypedContractMethod<[], [bigint], "view">;

  trigger: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "defaulting"
  ): TypedContractMethod<
    [
      _proof: IReferencedPaymentNonexistence.ProofStruct,
      _redemptionRequestId: BigNumberish,
      _trigger: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "diamond"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "howMuchIsMyNativeBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tempProof"
  ): TypedContractMethod<
    [],
    [IReferencedPaymentNonexistence.ResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "tempRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trigger"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
