/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MerkleTreeMockInterface extends Interface {
  getFunction(
    nameOrSignature: "calculateMerkleRoot" | "doubleHash"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateMerkleRoot",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "doubleHash", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "calculateMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doubleHash", data: BytesLike): Result;
}

export interface MerkleTreeMock extends BaseContract {
  connect(runner?: ContractRunner | null): MerkleTreeMock;
  waitForDeployment(): Promise<this>;

  interface: MerkleTreeMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateMerkleRoot: TypedContractMethod<
    [_leaves: BytesLike[]],
    [string],
    "view"
  >;

  doubleHash: TypedContractMethod<[_str: string], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateMerkleRoot"
  ): TypedContractMethod<[_leaves: BytesLike[]], [string], "view">;
  getFunction(
    nameOrSignature: "doubleHash"
  ): TypedContractMethod<[_str: string], [string], "view">;

  filters: {};
}
