/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondCutFacet } from "./DiamondCutFacet";
export type { DiamondInit } from "./DiamondInit";
export type { MockDiamond } from "./MockDiamond";
export type { Test1Facet } from "./Test1Facet";
export type { Test2Facet } from "./Test2Facet";
