/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CollateralPool } from "./CollateralPool";
export type { CollateralPoolFactory } from "./CollateralPoolFactory";
export type { CollateralPoolToken } from "./CollateralPoolToken";
export type { CollateralPoolTokenFactory } from "./CollateralPoolTokenFactory";
