/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  DistributionToDelegators,
  DistributionToDelegatorsInterface,
} from "../../../../contracts/assetManager/mock/DistributionToDelegators";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IWNat",
        name: "_wNat",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "OptedOutOfAirdrop",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    name: "claim",
    outputs: [
      {
        internalType: "uint256",
        name: "_rewardAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "optOutOfAirdrop",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161029238038061029283398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6101ff806100936000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063b2c121921461003b578063f2a1f76714610060575b600080fd5b61004e610049366004610156565b61006a565b60405190815260200160405180910390f35b6100686100f4565b005b6000805460405163a9059cbb60e01b81526001600160a01b038681166004830152670de0b6b3a76400006024830181905292169063a9059cbb906044016020604051808303816000875af11580156100c6573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100ea91906101a5565b5095945050505050565b6040513381527ff9ad59095575f64b755ef471a707947375ae7b973c102582ed669e54864fb06a9060200160405180910390a1565b80356001600160a01b038116811461014057600080fd5b919050565b801515811461015357600080fd5b50565b6000806000806080858703121561016c57600080fd5b61017585610129565b935061018360208601610129565b925060408501359150606085013561019a81610145565b939692955090935050565b6000602082840312156101b757600080fd5b81516101c281610145565b939250505056fea2646970667358221220c02c4bdda82e9d62490735c88627cde6ca072acb6afbaa124be04d036005f72564736f6c63430008170033";

type DistributionToDelegatorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DistributionToDelegatorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DistributionToDelegators__factory extends ContractFactory {
  constructor(...args: DistributionToDelegatorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _wNat: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_wNat, overrides || {});
  }
  override deploy(
    _wNat: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_wNat, overrides || {}) as Promise<
      DistributionToDelegators & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): DistributionToDelegators__factory {
    return super.connect(runner) as DistributionToDelegators__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DistributionToDelegatorsInterface {
    return new Interface(_abi) as DistributionToDelegatorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DistributionToDelegators {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as DistributionToDelegators;
  }
}
