/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MaliciousRewardManager,
  MaliciousRewardManagerInterface,
} from "../../../../contracts/assetManager/mock/MaliciousRewardManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_claim",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "amount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "uint24",
                name: "rewardEpochId",
                type: "uint24",
              },
              {
                internalType: "bytes20",
                name: "beneficiary",
                type: "bytes20",
              },
              {
                internalType: "uint120",
                name: "amount",
                type: "uint120",
              },
              {
                internalType: "enum RewardsV2Interface.ClaimType",
                name: "claimType",
                type: "uint8",
              },
            ],
            internalType: "struct RewardsV2Interface.RewardClaim",
            name: "body",
            type: "tuple",
          },
        ],
        internalType: "struct RewardsV2Interface.RewardClaimWithProof[]",
        name: "",
        type: "tuple[]",
      },
    ],
    name: "claim",
    outputs: [
      {
        internalType: "uint256",
        name: "_rewardAmountWei",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405260008055348015601357600080fd5b506040516101f13803806101f18339810160408190526030916037565b600055604f565b600060208284031215604857600080fd5b5051919050565b6101938061005e6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80638e33aba51461003b578063aa8c217c14610068575b600080fd5b610056610049366004610089565b6000549695505050505050565b60405190815260200160405180910390f35b61005660005481565b6001600160a01b038116811461008657600080fd5b50565b60008060008060008060a087890312156100a257600080fd5b86356100ad81610071565b955060208701356100bd81610071565b9450604087013562ffffff811681146100d557600080fd5b9350606087013580151581146100ea57600080fd5b9250608087013567ffffffffffffffff81111561010657600080fd5b8701600080601f83018b13610119578182fd5b50813567ffffffffffffffff811115610130578182fd5b6020830191508a60208260051b850101111561014b57600080fd5b979a969950949750929593949250505056fea26469706673582212202ed5cfeba0f93587d9efcdbaf627ab79dfa7ba393f218f93a5fae21581fa2eda64736f6c634300081b0033";

type MaliciousRewardManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousRewardManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousRewardManager__factory extends ContractFactory {
  constructor(...args: MaliciousRewardManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _claim: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_claim, overrides || {});
  }
  override deploy(
    _claim: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_claim, overrides || {}) as Promise<
      MaliciousRewardManager & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MaliciousRewardManager__factory {
    return super.connect(runner) as MaliciousRewardManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousRewardManagerInterface {
    return new Interface(_abi) as MaliciousRewardManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousRewardManager {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MaliciousRewardManager;
  }
}
