/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AgentOwnerRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptWorkAddressAssignment"
      | "cancelGovernanceCall"
      | "executeGovernanceCall"
      | "getAgentDescription"
      | "getAgentIconUrl"
      | "getAgentName"
      | "getAgentTermsOfUseUrl"
      | "getManagementAddress"
      | "getPendingWorkAddress"
      | "getWorkAddress"
      | "governance"
      | "governanceSettings"
      | "initialize"
      | "isExecutor"
      | "isWhitelisted"
      | "manager"
      | "productionMode"
      | "proxiableUUID"
      | "revokeAddress"
      | "setAgentDescription"
      | "setAgentIconUrl"
      | "setAgentName"
      | "setAgentTermsOfUseUrl"
      | "setManager"
      | "setWorkAddress"
      | "supportsInterface"
      | "switchToProductionMode"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "whitelistAndDescribeAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "AgentDataChanged"
      | "BeaconUpgraded"
      | "GovernanceCallTimelocked"
      | "GovernanceInitialised"
      | "GovernedProductionModeEntered"
      | "ManagerChanged"
      | "TimelockedGovernanceCallCanceled"
      | "TimelockedGovernanceCallExecuted"
      | "Upgraded"
      | "Whitelisted"
      | "WhitelistingRevoked"
      | "WorkAddressChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptWorkAddressAssignment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelGovernanceCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeGovernanceCall",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentDescription",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentIconUrl",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentName",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentTermsOfUseUrl",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getManagementAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingWorkAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceSettings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "productionMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentDescription",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentIconUrl",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentName",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentTermsOfUseUrl",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWorkAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "switchToProductionMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistAndDescribeAgent",
    values: [AddressLike, string, string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptWorkAddressAssignment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelGovernanceCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeGovernanceCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentIconUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentTermsOfUseUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManagementAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingWorkAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExecutor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "productionMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentIconUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentTermsOfUseUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWorkAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "switchToProductionMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAndDescribeAgent",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentDataChangedEvent {
  export type InputTuple = [
    managementAddress: AddressLike,
    name: string,
    description: string,
    iconUrl: string,
    termsOfUseUrl: string
  ];
  export type OutputTuple = [
    managementAddress: string,
    name: string,
    description: string,
    iconUrl: string,
    termsOfUseUrl: string
  ];
  export interface OutputObject {
    managementAddress: string;
    name: string;
    description: string;
    iconUrl: string;
    termsOfUseUrl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceCallTimelockedEvent {
  export type InputTuple = [
    encodedCall: BytesLike,
    encodedCallHash: BytesLike,
    allowedAfterTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    encodedCall: string,
    encodedCallHash: string,
    allowedAfterTimestamp: bigint
  ];
  export interface OutputObject {
    encodedCall: string;
    encodedCallHash: string;
    allowedAfterTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceInitialisedEvent {
  export type InputTuple = [initialGovernance: AddressLike];
  export type OutputTuple = [initialGovernance: string];
  export interface OutputObject {
    initialGovernance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernedProductionModeEnteredEvent {
  export type InputTuple = [governanceSettings: AddressLike];
  export type OutputTuple = [governanceSettings: string];
  export interface OutputObject {
    governanceSettings: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerChangedEvent {
  export type InputTuple = [manager: AddressLike];
  export type OutputTuple = [manager: string];
  export interface OutputObject {
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedGovernanceCallCanceledEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockedGovernanceCallExecutedEvent {
  export type InputTuple = [encodedCallHash: BytesLike];
  export type OutputTuple = [encodedCallHash: string];
  export interface OutputObject {
    encodedCallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistedEvent {
  export type InputTuple = [value: AddressLike];
  export type OutputTuple = [value: string];
  export interface OutputObject {
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistingRevokedEvent {
  export type InputTuple = [value: AddressLike];
  export type OutputTuple = [value: string];
  export interface OutputObject {
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkAddressChangedEvent {
  export type InputTuple = [
    managementAddress: AddressLike,
    prevWorkAddress: AddressLike,
    workAddress: AddressLike
  ];
  export type OutputTuple = [
    managementAddress: string,
    prevWorkAddress: string,
    workAddress: string
  ];
  export interface OutputObject {
    managementAddress: string;
    prevWorkAddress: string;
    workAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentOwnerRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentOwnerRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentOwnerRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptWorkAddressAssignment: TypedContractMethod<
    [_managementAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelGovernanceCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  executeGovernanceCall: TypedContractMethod<
    [_encodedCall: BytesLike],
    [void],
    "nonpayable"
  >;

  getAgentDescription: TypedContractMethod<
    [_managementAddress: AddressLike],
    [string],
    "view"
  >;

  getAgentIconUrl: TypedContractMethod<
    [_managementAddress: AddressLike],
    [string],
    "view"
  >;

  getAgentName: TypedContractMethod<
    [_managementAddress: AddressLike],
    [string],
    "view"
  >;

  getAgentTermsOfUseUrl: TypedContractMethod<
    [_managementAddress: AddressLike],
    [string],
    "view"
  >;

  getManagementAddress: TypedContractMethod<
    [_workAddress: AddressLike],
    [string],
    "view"
  >;

  getPendingWorkAddress: TypedContractMethod<
    [_managementAddress: AddressLike],
    [string],
    "view"
  >;

  getWorkAddress: TypedContractMethod<
    [_managementAddress: AddressLike],
    [string],
    "view"
  >;

  governance: TypedContractMethod<[], [string], "view">;

  governanceSettings: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [_governanceSettings: AddressLike, _initialGovernance: AddressLike],
    [void],
    "nonpayable"
  >;

  isExecutor: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isWhitelisted: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  manager: TypedContractMethod<[], [string], "view">;

  productionMode: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  revokeAddress: TypedContractMethod<
    [_address: AddressLike],
    [void],
    "nonpayable"
  >;

  setAgentDescription: TypedContractMethod<
    [_managementAddress: AddressLike, _description: string],
    [void],
    "nonpayable"
  >;

  setAgentIconUrl: TypedContractMethod<
    [_managementAddress: AddressLike, _iconUrl: string],
    [void],
    "nonpayable"
  >;

  setAgentName: TypedContractMethod<
    [_managementAddress: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;

  setAgentTermsOfUseUrl: TypedContractMethod<
    [_managementAddress: AddressLike, _touUrl: string],
    [void],
    "nonpayable"
  >;

  setManager: TypedContractMethod<
    [_manager: AddressLike],
    [void],
    "nonpayable"
  >;

  setWorkAddress: TypedContractMethod<
    [_workAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [_interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  switchToProductionMode: TypedContractMethod<[], [void], "nonpayable">;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  whitelistAndDescribeAgent: TypedContractMethod<
    [
      _managementAddress: AddressLike,
      _name: string,
      _description: string,
      _iconUrl: string,
      _touUrl: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptWorkAddressAssignment"
  ): TypedContractMethod<
    [_managementAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelGovernanceCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeGovernanceCall"
  ): TypedContractMethod<[_encodedCall: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentDescription"
  ): TypedContractMethod<[_managementAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentIconUrl"
  ): TypedContractMethod<[_managementAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentName"
  ): TypedContractMethod<[_managementAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentTermsOfUseUrl"
  ): TypedContractMethod<[_managementAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getManagementAddress"
  ): TypedContractMethod<[_workAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPendingWorkAddress"
  ): TypedContractMethod<[_managementAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getWorkAddress"
  ): TypedContractMethod<[_managementAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "governanceSettings"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_governanceSettings: AddressLike, _initialGovernance: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isExecutor"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "manager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "productionMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeAddress"
  ): TypedContractMethod<[_address: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentDescription"
  ): TypedContractMethod<
    [_managementAddress: AddressLike, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentIconUrl"
  ): TypedContractMethod<
    [_managementAddress: AddressLike, _iconUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentName"
  ): TypedContractMethod<
    [_managementAddress: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentTermsOfUseUrl"
  ): TypedContractMethod<
    [_managementAddress: AddressLike, _touUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setManager"
  ): TypedContractMethod<[_manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWorkAddress"
  ): TypedContractMethod<[_workAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[_interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "switchToProductionMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "whitelistAndDescribeAgent"
  ): TypedContractMethod<
    [
      _managementAddress: AddressLike,
      _name: string,
      _description: string,
      _iconUrl: string,
      _touUrl: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "AgentDataChanged"
  ): TypedContractEvent<
    AgentDataChangedEvent.InputTuple,
    AgentDataChangedEvent.OutputTuple,
    AgentDataChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceCallTimelocked"
  ): TypedContractEvent<
    GovernanceCallTimelockedEvent.InputTuple,
    GovernanceCallTimelockedEvent.OutputTuple,
    GovernanceCallTimelockedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceInitialised"
  ): TypedContractEvent<
    GovernanceInitialisedEvent.InputTuple,
    GovernanceInitialisedEvent.OutputTuple,
    GovernanceInitialisedEvent.OutputObject
  >;
  getEvent(
    key: "GovernedProductionModeEntered"
  ): TypedContractEvent<
    GovernedProductionModeEnteredEvent.InputTuple,
    GovernedProductionModeEnteredEvent.OutputTuple,
    GovernedProductionModeEnteredEvent.OutputObject
  >;
  getEvent(
    key: "ManagerChanged"
  ): TypedContractEvent<
    ManagerChangedEvent.InputTuple,
    ManagerChangedEvent.OutputTuple,
    ManagerChangedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedGovernanceCallCanceled"
  ): TypedContractEvent<
    TimelockedGovernanceCallCanceledEvent.InputTuple,
    TimelockedGovernanceCallCanceledEvent.OutputTuple,
    TimelockedGovernanceCallCanceledEvent.OutputObject
  >;
  getEvent(
    key: "TimelockedGovernanceCallExecuted"
  ): TypedContractEvent<
    TimelockedGovernanceCallExecutedEvent.InputTuple,
    TimelockedGovernanceCallExecutedEvent.OutputTuple,
    TimelockedGovernanceCallExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Whitelisted"
  ): TypedContractEvent<
    WhitelistedEvent.InputTuple,
    WhitelistedEvent.OutputTuple,
    WhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistingRevoked"
  ): TypedContractEvent<
    WhitelistingRevokedEvent.InputTuple,
    WhitelistingRevokedEvent.OutputTuple,
    WhitelistingRevokedEvent.OutputObject
  >;
  getEvent(
    key: "WorkAddressChanged"
  ): TypedContractEvent<
    WorkAddressChangedEvent.InputTuple,
    WorkAddressChangedEvent.OutputTuple,
    WorkAddressChangedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "AgentDataChanged(address,string,string,string,string)": TypedContractEvent<
      AgentDataChangedEvent.InputTuple,
      AgentDataChangedEvent.OutputTuple,
      AgentDataChangedEvent.OutputObject
    >;
    AgentDataChanged: TypedContractEvent<
      AgentDataChangedEvent.InputTuple,
      AgentDataChangedEvent.OutputTuple,
      AgentDataChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "GovernanceCallTimelocked(bytes,bytes32,uint256)": TypedContractEvent<
      GovernanceCallTimelockedEvent.InputTuple,
      GovernanceCallTimelockedEvent.OutputTuple,
      GovernanceCallTimelockedEvent.OutputObject
    >;
    GovernanceCallTimelocked: TypedContractEvent<
      GovernanceCallTimelockedEvent.InputTuple,
      GovernanceCallTimelockedEvent.OutputTuple,
      GovernanceCallTimelockedEvent.OutputObject
    >;

    "GovernanceInitialised(address)": TypedContractEvent<
      GovernanceInitialisedEvent.InputTuple,
      GovernanceInitialisedEvent.OutputTuple,
      GovernanceInitialisedEvent.OutputObject
    >;
    GovernanceInitialised: TypedContractEvent<
      GovernanceInitialisedEvent.InputTuple,
      GovernanceInitialisedEvent.OutputTuple,
      GovernanceInitialisedEvent.OutputObject
    >;

    "GovernedProductionModeEntered(address)": TypedContractEvent<
      GovernedProductionModeEnteredEvent.InputTuple,
      GovernedProductionModeEnteredEvent.OutputTuple,
      GovernedProductionModeEnteredEvent.OutputObject
    >;
    GovernedProductionModeEntered: TypedContractEvent<
      GovernedProductionModeEnteredEvent.InputTuple,
      GovernedProductionModeEnteredEvent.OutputTuple,
      GovernedProductionModeEnteredEvent.OutputObject
    >;

    "ManagerChanged(address)": TypedContractEvent<
      ManagerChangedEvent.InputTuple,
      ManagerChangedEvent.OutputTuple,
      ManagerChangedEvent.OutputObject
    >;
    ManagerChanged: TypedContractEvent<
      ManagerChangedEvent.InputTuple,
      ManagerChangedEvent.OutputTuple,
      ManagerChangedEvent.OutputObject
    >;

    "TimelockedGovernanceCallCanceled(bytes32)": TypedContractEvent<
      TimelockedGovernanceCallCanceledEvent.InputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputObject
    >;
    TimelockedGovernanceCallCanceled: TypedContractEvent<
      TimelockedGovernanceCallCanceledEvent.InputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputTuple,
      TimelockedGovernanceCallCanceledEvent.OutputObject
    >;

    "TimelockedGovernanceCallExecuted(bytes32)": TypedContractEvent<
      TimelockedGovernanceCallExecutedEvent.InputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputObject
    >;
    TimelockedGovernanceCallExecuted: TypedContractEvent<
      TimelockedGovernanceCallExecutedEvent.InputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputTuple,
      TimelockedGovernanceCallExecutedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "Whitelisted(address)": TypedContractEvent<
      WhitelistedEvent.InputTuple,
      WhitelistedEvent.OutputTuple,
      WhitelistedEvent.OutputObject
    >;
    Whitelisted: TypedContractEvent<
      WhitelistedEvent.InputTuple,
      WhitelistedEvent.OutputTuple,
      WhitelistedEvent.OutputObject
    >;

    "WhitelistingRevoked(address)": TypedContractEvent<
      WhitelistingRevokedEvent.InputTuple,
      WhitelistingRevokedEvent.OutputTuple,
      WhitelistingRevokedEvent.OutputObject
    >;
    WhitelistingRevoked: TypedContractEvent<
      WhitelistingRevokedEvent.InputTuple,
      WhitelistingRevokedEvent.OutputTuple,
      WhitelistingRevokedEvent.OutputObject
    >;

    "WorkAddressChanged(address,address,address)": TypedContractEvent<
      WorkAddressChangedEvent.InputTuple,
      WorkAddressChangedEvent.OutputTuple,
      WorkAddressChangedEvent.OutputObject
    >;
    WorkAddressChanged: TypedContractEvent<
      WorkAddressChangedEvent.InputTuple,
      WorkAddressChangedEvent.OutputTuple,
      WorkAddressChangedEvent.OutputObject
    >;
  };
}
