/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AssetManagerBase,
  AssetManagerBaseInterface,
} from "../../../../contracts/assetManager/facets/AssetManagerBase";

const _abi = [
  {
    inputs: [],
    name: "EmergencyPauseActive",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAttached",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyAssetManagerController",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyImmediateGovernanceOrExecutor",
    type: "error",
  },
] as const;

export class AssetManagerBase__factory {
  static readonly abi = _abi;
  static createInterface(): AssetManagerBaseInterface {
    return new Interface(_abi) as AssetManagerBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AssetManagerBase {
    return new Contract(address, _abi, runner) as unknown as AssetManagerBase;
  }
}
