name: container-images

on:
  push:
    branches: [ "main" ]

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Set ALL_TAGS
      env:
        REPOSITORY: '${{ github.repository }}'
      run: |
        tags=("main")
        tags+=("latest")

        lc_repo=${REPOSITORY,,}

        image_paths=()
        for tag in ${tags[@]}; do
          image_paths+=("ghcr.io/$lc_repo:$tag")
        done

        ALL_TAGS=$(printf ',%s' "${image_paths[@]}")
        echo "ALL_TAGS=${ALL_TAGS:1}" >>$GITHUB_ENV

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push default image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.ALL_TAGS }}
